"use client";

import { createContext, ReactNode, useContext, useEffect, useState } from "react";

export type Language = "en" | "id";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const en: Record<string, string> = {
  "nav.about": "ROSCA",
  "nav.howItWorks": "How It Works",
  "nav.advantages": "Why Sui",
  "nav.pools": "Pools",
  "nav.faq": "FAQ",
  "nav.aiYield": "AI Yield",
  "nav.demo": "Demo",
  "nav.leaderboard": "Leaderboard",
  "nav.connectWallet": "Connect Wallet",

  "about.badge": "What is Suivan?",
  "about.title": "Community savings, rebuilt for",
  "about.titleHighlight": "Sui",
  "about.problemTitle": "Traditional ROSCA Gaps",
  "about.problemSubtitle": "Trust and coordination issues",
  "about.problem1.title": "Commitment risk",
  "about.problem1.desc": "Members need clear incentives to complete every cycle.",
  "about.problem2.title": "Idle funds",
  "about.problem2.desc": "Capital can sit unused between contributions and payouts.",
  "about.problem3.title": "Manual records",
  "about.problem3.desc": "Status, turns, and payments are hard to verify at scale.",
  "about.problem4.title": "Limited reach",
  "about.problem4.desc": "Local groups need infrastructure to coordinate globally.",
  "about.solutionTitle": "Suivan Direction",
  "about.solutionSubtitle": "Composable frontend for Sui ROSCA pools",
  "about.solution1.title": "Collateral visibility",
  "about.solution1.desc": "Surface commitment state without hardcoding old contract logic.",
  "about.solution2.title": "Yield signals",
  "about.solution2.desc": "Show APY and idle-fund opportunities through modular data boundaries.",
  "about.solution3.title": "Transparent cycle state",
  "about.solution3.desc": "Expose participant progress, payouts, and contribution status clearly.",
  "about.solution4.title": "Global pool UX",
  "about.solution4.desc": "Explain Arisan as a local ROSCA expression while keeping the product global.",
  "about.quote": "Community wealth works when rules are visible, cycles are clear, and members can coordinate across borders.",
  "about.quoteBrand": "Suivan",
  "about.quoteEnd": "makes that interface legible.",
  "about.cta": "See How It Works",

  "faq.badge": "FAQ",
  "faq.title": "Frequently Asked Questions",
  "faq.subtitle": "Answers about Suivan, ROSCA pools, Sui-native settlement, and the current frontend migration.",
  "faq.q1": "What is Suivan?",
  "faq.a1": "Suivan is a frontend direction for a global ROSCA protocol built around Sui-native community finance.",
  "faq.q2": "What is ROSCA?",
  "faq.a2": "ROSCA stands for Rotating Savings and Credit Association. Members contribute on a recurring cycle, and one member receives the pooled payout each round until everyone has received a turn.",
  "faq.q3": "How does Arisan relate to ROSCA?",
  "faq.a3": "Arisan is a local Indonesian expression of the broader ROSCA model. Suivan explains that cultural familiarity while keeping the product language accessible for a global audience.",
  "faq.q4": "Why build this on Sui?",
  "faq.a4": "Sui gives Suivan a strong direction for fast settlement, low fees, transparent object-oriented state, and scalable community finance experiences.",
  "faq.q5": "Are the contracts and API final?",
  "faq.a5": "No. The smart contract and backend layers are being rebuilt separately.",
  "faq.q6": "What pool data will the frontend show?",
  "faq.a6": "The frontend is prepared for pool lists, pool detail, join flow, contribution flow, participant status, cycle progress, APY signals, and yield summaries.",
  "faq.q7": "Is Suivan custodial?",
  "faq.a7": "The product direction is non-custodial. Final security, custody, and transaction details should follow the new Sui contract architecture once available.",
  "faq.q8": "How can I follow the project?",
  "faq.a8": "You can follow the Suivan community through Telegram and Discord while the protocol and frontend continue to evolve.",
  "faq.contactTitle": "Still have questions?",
  "faq.contactDesc": "Join the Suivan community channels for updates, feedback, and collaboration.",

  "landing.badge": "Sui community wealth",
  "landing.title": "Simple ROSCA pools for global communities.",
  "landing.subtitle": "Suivan explains Arisan as a local form of ROSCA, then turns it into a clean Sui-native interface for joining pools, tracking cycles, seeing member progress, and reading APY signals.",
  "landing.explore": "Explore Pools",
  "landing.how": "How ROSCA Works",
  "landing.statPools": "POOLS",
  "landing.statMembers": "MEMBERS",
  "landing.statVolume": "VOLUME",
  "landing.statApy": "APY",
  "landing.step1Title": "Join",
  "landing.step1Copy": "Pick a ROSCA pool, inspect the terms, and join only after the cycle rules are clear.",
  "landing.step2Title": "Contribute",
  "landing.step2Copy": "Every member gets a simple cycle status: ready, pending, contributed, or paid out.",
  "landing.step3Title": "Rotate",
  "landing.step3Copy": "Payouts rotate through the group while the frontend keeps progress visible.",
  "landing.step4Title": "Earn",
  "landing.step4Copy": "Idle funds can show APY signals without coupling the UI to unfinished contract logic.",
  "landing.sectionTitle": "Keep the product readable in four states.",
  "landing.sectionSub": "The UI should feel like a friendly protocol dashboard, not a crowded DeFi terminal.",
  "landing.walrusBadge": "walrus_inspired",
  "landing.walrusTitle": "Treat every pool like an inspectable Sui object.",
  "landing.walrusDesc": "Walrus keeps a complex protocol understandable through clear resources, objects, epochs, and availability. Suivan should do the same for ROSCA cycles.",
  "landing.trustBadge": "trust_layer",
  "landing.trustTitle": "Less noise. More confidence.",
  "landing.trustDesc": "Suivan should explain what matters before a user connects a wallet: contribution schedule, participant state, payout progress, collateral direction, and yield assumptions. Everything else can wait until the integration is real.",
  "pools.title": "Explore ROSCA Pools",
  "pools.subtitle": "Discover rotating savings pools with visible cycle state, participant progress, and APY signals.",
  "pools.totalPools": "TOTAL POOLS",
  "pools.open": "OPEN",
  "pools.active": "ACTIVE", 
  "pools.usdc": "USDC",
  "pools.create": "+ Create Custom Pool",
  "pools.connectWallet": "Connect wallet to create pool",
  "pools.join": "Join Pool",
  "pools.viewDetails": "View Details",
  "pools.emptyTitle": "No pools found",
  "pools.emptyDesc": "No pools have been created yet. Be the first to create one!",
  "pools.emptyFilter": "There are no {filter} pools at the moment.",
  "pools.joinTitle": "Join {name}",
  "pools.deposit": "Monthly Deposit",
  "pools.collateral": "Required Collateral",
  "pools.collateralDesc": "125% of remaining deposits, returned at cycle end plus yield bonus",
  "pools.estimatedApy": "Estimated APY",
  "pools.coinLabel": "USDC Coin",
  "pools.agree": "By joining, you agree to make monthly deposits for {count} months",
  "pools.createTitle": "Create Custom Pool",
  "pools.totalValue": "Total Pool Value",
  "pools.poolDuration": "Pool Duration",
  "pools.requiredCollateral": "Required Collateral (125%)",
  "detail.back": "Back to Pools",
  "detail.poolInfo": "Pool Information",
  "detail.deposit": "DEPOSIT",
  "detail.members": "MEMBERS",
  "detail.cycle": "CYCLE",
  "detail.funds": "FUNDS",
  "detail.capacity": "Pool Capacity",
  "detail.yieldSection": "Yield and Cycle Signals",
  "detail.yield": "YIELD",
  "detail.estApy": "EST APY",
  "detail.collateral": "COLLATERAL",
  "detail.participants": "Participants ({count})",
  "detail.noParticipants": "No participants yet. Be the first to join!",
  "detail.yourStatus": "Your Status",
  "detail.activeParticipant": "Active Participant",
  "detail.youAreIn": "You are part of this ROSCA pool",
  "detail.collateralLocked": "Collateral Locked",
  "detail.totalDeposited": "Total Deposited",
  "detail.receivedPayout": "Received Payout",
  "detail.yes": "Yes",
  "detail.notYet": "Not yet",
  "detail.makeDeposit": "Make Monthly Deposit",
  "detail.collateralAvailable": "Collateral Available",
  "detail.collateralReturned": "Your collateral + yield bonus has been returned automatically when the pool ended.",
  "detail.notParticipant": "You are not a participant in this pool.",
  "detail.joinThisPool": "Join This Pool",
  "detail.yourWallet": "Your Wallet",
  "detail.usdcBalance": "USDC Balance",
  "detail.coinsAvailable": "{count} coin(s) available",
  "detail.getStarted": "Get Started",
  "detail.connectPrompt": "Connect your wallet to join this pool or view your status",
  "ai.title": "Yield Signals",
  "ai.subtitle": "Real-time DeFi yields from Sui protocols, aggregated and analyzed for your ROSCA pool.",
  "demo.title": "How Suivan Works",
  "demo.step1Title": "Connect",
  "demo.step1Sub": "zkLogin — No Wallet Required",
  "demo.step2Title": "Join a Pool",
  "demo.step2Sub": "Pick Your ROSCA Circle",
  "demo.step3Title": "Contribute Monthly",
  "demo.step3Sub": "Automatic Cycle Deposits",
  "demo.step4Title": "Win the Pot",
  "demo.step4Sub": "Random Selection, Fair Payout",
  "demo.step5Title": "Settle & Earn Yield",
  "demo.step5Sub": "AI-Optimized Returns",
  "leaderboard.title": "Leaderboard",
  "leaderboard.subtitle": "Top participants ranked by total earnings and pool activity.",
  "footer.tagline": "A global ROSCA frontend for Sui-native cycles, pool state, yield signals, and community trust.",
  "footer.builtFor": "Built for Sui",
  "ai.badge": "yield_signals",
  "ai.loading": "Fetching live yields...",
  "ai.errorTitle": "FETCH ERROR",
  "ai.avgApy": "AVG APY",
  "ai.maxApy": "MAX APY",
  "ai.protocols": "PROTOCOLS",
  "ai.totalTvl": "TOTAL TVL",
  "ai.protocolYields": "Protocol Yields",
  "ai.trend": "Trend",
  "ai.marketConditions": "Market Conditions",
  "ai.volatilityIndex": "Volatility Index",
  "ai.gasPrice": "Reference Gas Price",
  "ai.direction": "Direction",
  "ai.yieldRecommendation": "Yield Recommendation",
  "ai.topProtocol": "Top",
  "ai.generateStrategy": "Generate Yield Strategy",
  "ai.recommendedProtocol": "Recommended",
  "ai.expectedApy": "Expected APY",
  "ai.riskReduction": "Risk Reduction",
  "ai.explorePools": "Explore Pools",
  "demo.badge": "demo_walkthrough",
  "demo.subtitle": "Five steps from zero to yield. No crypto knowledge needed.",
  "demo.step": "Step",
  "demo.step1Detail": "Sign in with Google via zkLogin. Suivan creates a Sui wallet for you automatically. No seed phrases, no browser extensions, no gas fees for first join.",
  "demo.step1Action": "Try Google Login",
  "demo.step2Detail": "Browse available pools (Small: 10 USDC, Medium: 50 USDC, Large: 100 USDC). Deposit collateral once — your commitment to the group. Sponsored transaction means you pay ZERO gas.",
  "demo.step2Action": "Sponsored Join",
  "demo.step3Detail": "Each cycle, deposit your share. Suivan tracks deposits per cycle — no double-deposit exploits. Miss a payment? Collateral is slashed proportionally.",
  "demo.step3Action": "Make Deposit",
  "demo.step4Detail": "One participant wins the pool each cycle. Selection uses on-chain entropy (tx digest + timestamp). Winner receives all cycle deposits + yield bonus.",
  "demo.step4Action": "Select Winner",
  "demo.step5Detail": "Idle pool funds are routed to Sui DeFi protocols (Cetus, NAVI, Scallop) for yield. APY signals from DeFiLlama — real data, real returns. After all cycles complete, collateral is returned.",
  "demo.step5Action": "View Yield Dashboard",
  "demo.feature1Title": "Zero Gas Fees",
  "demo.feature1Desc": "Sponsored transactions — join a pool without holding SUI.",
  "demo.feature2Title": "DeFi Yield",
  "demo.feature2Desc": "Idle funds routed to Sui protocols — real APY from DeFiLlama.",
  "demo.feature3Title": "On-Chain Metadata",
  "demo.feature3Desc": "Pool details stored on Walrus — permanent, decentralized.",
  "leaderboard.badge": "reputation_board",
  "leaderboard.statUsers": "USERS",
  "leaderboard.statEarned": "EARNED",
  "leaderboard.statAvgApy": "AVG APY",
  "leaderboard.sortEarned": "Earned",
  "leaderboard.sortPools": "Pools",
  "leaderboard.sortWinRate": "Win Rate",
  "leaderboard.you": "YOU",
  "leaderboard.pools": "pools",
};

const id: Record<string, string> = {
  "nav.about": "ROSCA",
  "nav.howItWorks": "Cara Kerja",
  "nav.advantages": "Mengapa Sui",
  "nav.pools": "Pool",
  "nav.faq": "FAQ",
  "nav.aiYield": "AI Yield",
  "nav.demo": "Demo",
  "nav.leaderboard": "Papan Skor",
  "nav.connectWallet": "Hubungkan Dompet",

  "about.badge": "Apa itu Suivan?",
  "about.title": "Tabungan komunitas, dibangun ulang untuk",
  "about.titleHighlight": "Sui",
  "about.problemTitle": "Kekurangan ROSCA Tradisional",
  "about.problemSubtitle": "Masalah kepercayaan dan koordinasi",
  "about.problem1.title": "Risiko komitmen",
  "about.problem1.desc": "Anggota butuh insentif jelas untuk menyelesaikan setiap siklus.",
  "about.problem2.title": "Dana menganggur",
  "about.problem2.desc": "Modal bisa tidak terpakai di antara kontribusi dan pembayaran.",
  "about.problem3.title": "Catatan manual",
  "about.problem3.desc": "Status, giliran, dan pembayaran sulit diverifikasi secara luas.",
  "about.problem4.title": "Jangkauan terbatas",
  "about.problem4.desc": "Kelompok lokal butuh infrastruktur untuk berkoordinasi secara global.",
  "about.solutionTitle": "Arah Suivan",
  "about.solutionSubtitle": "Frontend komposable untuk pool ROSCA di Sui",
  "about.solution1.title": "Visibilitas jaminan",
  "about.solution1.desc": "Tampilkan status komitmen tanpa mengunci logika kontrak lama.",
  "about.solution2.title": "Sinyal yield",
  "about.solution2.desc": "Tampilkan APY dan peluang dana menganggur melalui batasan data modular.",
  "about.solution3.title": "Status siklus transparan",
  "about.solution3.desc": "Tampilkan progres partisipan, pembayaran, dan status kontribusi dengan jelas.",
  "about.solution4.title": "UX pool global",
  "about.solution4.desc": "Jelaskan Arisan sebagai ekspresi ROSCA lokal sambil menjaga produk tetap global.",
  "about.quote": "Kekayaan komunitas bekerja saat aturan terlihat, siklus jelas, dan anggota bisa berkoordinasi lintas batas.",
  "about.quoteBrand": "Suivan",
  "about.quoteEnd": "membuat antarmuka itu mudah dibaca.",
  "about.cta": "Lihat Cara Kerja",

  "faq.badge": "FAQ",
  "faq.title": "Pertanyaan Umum",
  "faq.subtitle": "Jawaban tentang Suivan, pool ROSCA, penyelesaian Sui-native, dan migrasi frontend.",
  "faq.q1": "Apa itu Suivan?",
  "faq.a1": "Suivan adalah frontend untuk protokol ROSCA global yang dibangun di atas keuangan komunitas Sui-native.",
  "faq.q2": "Apa itu ROSCA?",
  "faq.a2": "ROSCA adalah singkatan dari Rotating Savings and Credit Association. Anggota berkontribusi dalam siklus berulang, dan satu anggota menerima pembayaran kumpulan setiap putaran hingga semua mendapat giliran.",
  "faq.q3": "Bagaimana hubungan Arisan dengan ROSCA?",
  "faq.a3": "Arisan adalah ekspresi lokal Indonesia dari model ROSCA yang lebih luas. Suivan menjelaskan keakraban budaya itu sambil menjaga bahasa produk dapat diakses secara global.",
  "faq.q4": "Mengapa dibangun di Sui?",
  "faq.a4": "Sui memberi Suivan arah yang kuat untuk penyelesaian cepat, biaya rendah, state berorientasi objek yang transparan, dan pengalaman keuangan komunitas yang skalabel.",
  "faq.q5": "Apakah kontrak dan API sudah final?",
  "faq.a5": "Belum. Layer kontrak pintar dan backend sedang dibangun ulang secara terpisah.",
  "faq.q6": "Data pool apa yang akan ditampilkan frontend?",
  "faq.a6": "Frontend siap untuk daftar pool, detail pool, alur join, alur kontribusi, status partisipan, progres siklus, sinyal APY, dan ringkasan yield.",
  "faq.q7": "Apakah Suivan kustodial?",
  "faq.a7": "Arah produk adalah non-kustodial. Detail keamanan, kustodi, dan transaksi akhir akan mengikuti arsitektur kontrak Sui yang baru.",
  "faq.q8": "Bagaimana cara mengikuti proyek ini?",
  "faq.a8": "Anda dapat mengikuti komunitas Suivan melalui Telegram dan Discord sementara protokol dan frontend terus berkembang.",
  "faq.contactTitle": "Masih ada pertanyaan?",
  "faq.contactDesc": "Bergabunglah dengan saluran komunitas Suivan untuk pembaruan, umpan balik, dan kolaborasi.",

  "landing.badge": "Kekayaan komunitas Sui",
  "landing.title": "Pool ROSCA sederhana untuk komunitas global.",
  "landing.subtitle": "Suivan menjelaskan Arisan sebagai bentuk lokal ROSCA, lalu mengubahnya menjadi antarmuka Sui-native untuk bergabung dengan pool, melacak siklus, melihat progres anggota, dan membaca sinyal APY.",
  "landing.explore": "Jelajahi Pool",
  "landing.how": "Cara Kerja ROSCA",
  "landing.statPools": "POOL",
  "landing.statMembers": "ANGGOTA",
  "landing.statVolume": "VOLUME",
  "landing.statApy": "APY",
  "landing.step1Title": "Gabung",
  "landing.step1Copy": "Pilih pool ROSCA, periksa ketentuannya, dan bergabung hanya setelah aturan siklus jelas.",
  "landing.step2Title": "Kontribusi",
  "landing.step2Copy": "Setiap anggota mendapat status siklus sederhana: siap, tertunda, berkontribusi, atau sudah dibayar.",
  "landing.step3Title": "Bergilir",
  "landing.step3Copy": "Pembayaran bergilir melalui grup sementara frontend menjaga progres tetap terlihat.",
  "landing.step4Title": "Hasilkan",
  "landing.step4Copy": "Dana menganggur dapat menunjukkan sinyal APY tanpa menghubungkan UI ke logika kontrak yang belum selesai.",
  "landing.sectionTitle": "Jaga produk tetap mudah dibaca dalam empat status.",
  "landing.sectionSub": "UI harus terasa seperti dashboard protokol yang ramah, bukan terminal DeFi yang penuh sesak.",
  "landing.walrusBadge": "terinspirasi_walrus",
  "landing.walrusTitle": "Perlakukan setiap pool seperti objek Sui yang dapat diperiksa.",
  "landing.walrusDesc": "Walrus menjaga protokol kompleks tetap mudah dipahami melalui sumber daya, objek, epoch, dan ketersediaan yang jelas. Suivan harus melakukan hal yang sama untuk siklus ROSCA.",
  "landing.trustBadge": "lapisan_kepercayaan",
  "landing.trustTitle": "Lebih sedikit kebisingan. Lebih percaya diri.",
  "landing.trustDesc": "Suivan harus menjelaskan apa yang penting sebelum pengguna menghubungkan dompet: jadwal kontribusi, status peserta, progres pembayaran, arah jaminan, dan asumsi yield. Semua yang lain bisa menunggu sampai integrasi selesai.",
  "pools.title": "Jelajahi Pool ROSCA",
  "pools.subtitle": "Temukan pool tabungan bergilir dengan status siklus yang terlihat, progres peserta, dan sinyal APY.",
  "pools.totalPools": "TOTAL POOL",
  "pools.open": "TERBUKA",
  "pools.active": "AKTIF",
  "pools.usdc": "USDC",
  "pools.create": "+ Buat Pool Kustom",
  "pools.connectWallet": "Hubungkan dompet untuk membuat pool",
  "pools.join": "Gabung Pool",
  "pools.viewDetails": "Lihat Detail",
  "pools.emptyTitle": "Tidak ada pool ditemukan",
  "pools.emptyDesc": "Belum ada pool yang dibuat. Jadilah yang pertama!",
  "pools.emptyFilter": "Tidak ada pool {filter} saat ini.",
  "pools.joinTitle": "Gabung {name}",
  "pools.deposit": "Setoran Bulanan",
  "pools.collateral": "Jaminan Diperlukan",
  "pools.collateralDesc": "125% dari sisa setoran, dikembalikan di akhir siklus ditambah bonus yield",
  "pools.estimatedApy": "Estimasi APY",
  "pools.coinLabel": "Koin USDC",
  "pools.agree": "Dengan bergabung, Anda setuju untuk melakukan setoran bulanan selama {count} bulan",
  "pools.createTitle": "Buat Pool Kustom",
  "pools.totalValue": "Total Nilai Pool",
  "pools.poolDuration": "Durasi Pool",
  "pools.requiredCollateral": "Jaminan Diperlukan (125%)",
  "detail.back": "Kembali ke Pool",
  "detail.poolInfo": "Informasi Pool",
  "detail.deposit": "SETORAN",
  "detail.members": "ANGGOTA",
  "detail.cycle": "SIKLUS",
  "detail.funds": "DANA",
  "detail.capacity": "Kapasitas Pool",
  "detail.yieldSection": "Sinyal Yield dan Siklus",
  "detail.yield": "YIELD",
  "detail.estApy": "EST APY",
  "detail.collateral": "JAMINAN",
  "detail.participants": "Peserta ({count})",
  "detail.noParticipants": "Belum ada peserta. Jadilah yang pertama!",
  "detail.yourStatus": "Status Anda",
  "detail.activeParticipant": "Peserta Aktif",
  "detail.youAreIn": "Anda adalah bagian dari pool ROSCA ini",
  "detail.collateralLocked": "Jaminan Terkunci",
  "detail.totalDeposited": "Total Disetor",
  "detail.receivedPayout": "Sudah Dibayar",
  "detail.yes": "Ya",
  "detail.notYet": "Belum",
  "detail.makeDeposit": "Lakukan Setoran Bulanan",
  "detail.collateralAvailable": "Jaminan Tersedia",
  "detail.collateralReturned": "Jaminan + bonus yield Anda telah dikembalikan secara otomatis saat pool berakhir.",
  "detail.notParticipant": "Anda bukan peserta di pool ini.",
  "detail.joinThisPool": "Gabung Pool Ini",
  "detail.yourWallet": "Dompet Anda",
  "detail.usdcBalance": "Saldo USDC",
  "detail.coinsAvailable": "{count} koin tersedia",
  "detail.getStarted": "Mulai",
  "detail.connectPrompt": "Hubungkan dompet Anda untuk bergabung dengan pool ini atau lihat status Anda",
  "ai.title": "Sinyal Yield",
  "ai.subtitle": "Yield DeFi real-time dari protokol Sui, dikumpulkan dan dianalisis untuk pool ROSCA Anda.",
  "demo.title": "Cara Kerja Suivan",
  "demo.step1Title": "Hubungkan",
  "demo.step1Sub": "zkLogin — Tanpa Dompet",
  "demo.step2Title": "Gabung Pool",
  "demo.step2Sub": "Pilih Lingkaran ROSCA Anda",
  "demo.step3Title": "Kontribusi Bulanan",
  "demo.step3Sub": "Setoran Siklus Otomatis",
  "demo.step4Title": "Menang",
  "demo.step4Sub": "Seleksi Acak, Pembayaran Adil",
  "demo.step5Title": "Selesaikan & Hasilkan Yield",
  "demo.step5Sub": "Pengembalian Dioptimalkan AI",
  "leaderboard.title": "Papan Skor",
  "leaderboard.subtitle": "Peserta teratas diperingkatkan berdasarkan total pendapatan dan aktivitas pool.",
  "footer.tagline": "Frontend ROSCA global untuk siklus Sui-native, status pool, sinyal yield, dan kepercayaan komunitas.",
  "footer.builtFor": "Dibangun untuk Sui",
  "ai.badge": "sinyal_yield",
  "ai.loading": "Mengambil data yield...",
  "ai.errorTitle": "KESALAHAN",
  "ai.avgApy": "RATA-RATA APY",
  "ai.maxApy": "APY MAKS",
  "ai.protocols": "PROTOKOL",
  "ai.totalTvl": "TOTAL TVL",
  "ai.protocolYields": "Yield Protokol",
  "ai.trend": "Tren",
  "ai.marketConditions": "Kondisi Pasar",
  "ai.volatilityIndex": "Indeks Volatilitas",
  "ai.gasPrice": "Harga Referensi Gas",
  "ai.direction": "Arah",
  "ai.yieldRecommendation": "Rekomendasi Yield",
  "ai.topProtocol": "Teratas",
  "ai.generateStrategy": "Buat Strategi Yield",
  "ai.recommendedProtocol": "Rekomendasi",
  "ai.expectedApy": "APY Diprediksi",
  "ai.riskReduction": "Reduksi Risiko",
  "ai.explorePools": "Jelajahi Pool",
  "demo.badge": "panduan_demo",
  "demo.subtitle": "Lima langkah dari nol hingga yield. Tidak perlu pengetahuan kripto.",
  "demo.step": "Langkah",
  "demo.step1Detail": "Masuk dengan Google via zkLogin. Suivan membuat dompet Sui secara otomatis. Tanpa seed phrase, tanpa ekstensi browser, tanpa biaya gas untuk bergabung pertama.",
  "demo.step1Action": "Coba Login Google",
  "demo.step2Detail": "Jelajahi pool yang tersedia (Kecil: 10 USDC, Sedang: 50 USDC, Besar: 100 USDC). Setor jaminan sekali — komitmen Anda ke grup. Transaksi disponsori berarti Anda membayar NOL gas.",
  "demo.step2Action": "Gabung Sponsored",
  "demo.step3Detail": "Setiap siklus, setorkan bagian Anda. Suivan melacak setoran per siklus — tidak ada eksploitasi setoran ganda. Tidak bayar? Jaminan dipotong secara proporsional.",
  "demo.step3Action": "Lakukan Setoran",
  "demo.step4Detail": "Satu peserta memenangkan pool setiap siklus. Seleksi menggunakan entropi on-chain (tx digest + timestamp). Pemenang menerima semua setoran siklus + bonus yield.",
  "demo.step4Action": "Pilih Pemenang",
  "demo.step5Detail": "Dana idle pool dialihkan ke protokol DeFi Sui (Cetus, NAVI, Scallop) untuk yield. Sinyal APY dari DeFiLlama — data nyata, hasil nyata. Setelah semua siklus selesai, jaminan dikembalikan.",
  "demo.step5Action": "Lihat Dashboard Yield",
  "demo.feature1Title": "Biaya Gas Nol",
  "demo.feature1Desc": "Transaksi disponsori — gabung pool tanpa memiliki SUI.",
  "demo.feature2Title": "Yield DeFi",
  "demo.feature2Desc": "Dana idle dialihkan ke protokol Sui — APY nyata dari DeFiLlama.",
  "demo.feature3Title": "Metadata On-Chain",
  "demo.feature3Desc": "Detail pool disimpan di Walrus — permanen, terdesentralisasi.",
  "leaderboard.badge": "papan_reputasi",
  "leaderboard.statUsers": "PENGGUNA",
  "leaderboard.statEarned": "HASIL",
  "leaderboard.statAvgApy": "RATA APY",
  "leaderboard.sortEarned": "Hasil",
  "leaderboard.sortPools": "Pool",
  "leaderboard.sortWinRate": "Menang",
  "leaderboard.you": "ANDA",
  "leaderboard.pools": "pool",
};

const translations: Record<Language, Record<string, string>> = { en, id };

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const stored = localStorage.getItem("suivan-language") as Language | null;
    if (stored === "en" || stored === "id") {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("suivan-language", lang);
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language]?.[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t } as LanguageContextType}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
