"use client";

import { createContext, ReactNode, useContext, useState } from "react";

export type Language = "en" | "id";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const en: Record<string, string> = {
  "nav.about": "ROSCA",
  "nav.howItWorks": "How It Works",
  "nav.advantages": "Why Sui",
  "nav.pools": "Pools",
  "nav.simulator": "Simulator",
  "nav.yield": "Yield Explorer",
  "nav.leaderboard": "Leaderboard",
  "nav.profile": "Profile",
  "nav.faq": "FAQ",
  "nav.faucet": "Faucet",
  "nav.demo": "Demo",
  "nav.yieldDemo": "Yield Engine",
  "nav.connectWallet": "Connect Wallet",

  "about.badge": "What is Suivan?",
  "about.title": "Community savings, rebuilt for",
  "about.titleHighlight": "Sui",
  "about.problemTitle": "Traditional ROSCA Gaps",
  "about.problemSubtitle": "Trust and coordination issues",
  "about.problem1.title": "Commitment risk",
  "about.problem1.desc": "Members need clear incentives to complete every cycle.",
  "about.problem2.title": "Idle funds",
  "about.problem2.desc": "Capital can sit unused between contributions and payouts.",
  "about.problem3.title": "Manual records",
  "about.problem3.desc": "Status, turns, and payments are hard to verify at scale.",
  "about.problem4.title": "Limited reach",
  "about.problem4.desc": "Local groups need infrastructure to coordinate globally.",
  "about.solutionTitle": "Suivan Direction",
  "about.solutionSubtitle": "Composable frontend for Sui ROSCA pools",
  "about.solution1.title": "Collateral visibility",
  "about.solution1.desc": "Surface commitment state without hardcoding old contract logic.",
  "about.solution2.title": "Yield signals",
  "about.solution2.desc": "Show APY and idle-fund opportunities through modular data boundaries.",
  "about.solution3.title": "Transparent cycle state",
  "about.solution3.desc": "Expose participant progress, payouts, and contribution status clearly.",
  "about.solution4.title": "Global pool UX",
  "about.solution4.desc": "Explain Arisan as a local ROSCA expression while keeping the product global.",
  "about.quote": "Community wealth works when rules are visible, cycles are clear, and members can coordinate across borders.",
  "about.quoteBrand": "Suivan",
  "about.quoteEnd": "makes that interface legible.",
  "about.cta": "See How It Works",

  "faq.badge": "FAQ",
  "faq.title": "Frequently Asked Questions",
  "faq.subtitle": "Everything you need to know about Suivan, ROSCA pools, and how to start saving on Sui.",

  "faq.q1": "What is Suivan?",
  "faq.a1": "Suivan is an on-chain ROSCA protocol built on Sui Move. It brings traditional rotating savings into DeFi — community members contribute monthly, winners are randomly selected via Seal RNG, and idle funds earn yield through AI-optimized DeFi strategies. No treasurer, no middleman, fully transparent smart contracts.",

  "faq.q2": "What is ROSCA?",
  "faq.a2": "ROSCA (Rotating Savings and Credit Association) is a global savings model practiced by billions — known as Arisan in Indonesia, Chit Fund in India, Tanda in Mexico, and many more. Members contribute a fixed amount each cycle. Each cycle, one member receives the entire pooled payout. This repeats until everyone has had a turn.",

  "faq.q3": "How do I start using Suivan?",
  "faq.a3": "Just connect your wallet — Suivan supports zkLogin, so you can sign in with Google or any OAuth provider, no seed phrase required. Head to /faucet to claim free test SUI and 500 USDC. Then explore /pools, pick one that fits your budget, and join. Your first transaction's gas is ultra-low on Sui (~0.0001 SUI).",

  "faq.q4": "Why Sui? What makes it different?",
  "faq.a4": "Sui's object-centric model makes every pool a live on-chain object you can inspect at any time. Sub-second finality means instant settlement. Gas fees are fractions of a cent (~$0.0003). zkLogin removes wallet complexity. Seal RNG provides verifiable fair random winner selection. Walrus stores pool metadata permanently. This stack is impossible on any other chain.",

  "faq.q5": "How does the collateral system work?",
  "faq.a5": "Every participant deposits 125% collateral upfront — calculated as 1.25 × (remaining contributions). This guarantees commitment. If you miss a payment, your collateral is slashed proportionally. If you complete all cycles faithfully, your full collateral is returned PLUS proportional yield earned during the pool's lifetime. This eliminates the traditional ROSCA risk of members running away after their turn.",

  "faq.q6": "How are winners selected?",
  "faq.a6": "Winners are selected randomly each cycle using Seal RNG — Sui's native on-chain random number generator. This guarantees fair, verifiable, and tamper-proof selection. No admin, no manual drawing, no bias. The randomness proof is recorded on-chain for anyone to verify.",

  "faq.q7": "How does yield work?",
  "faq.a7": "While funds sit idle between cycles, our AI Yield Optimizer deploys them across Sui DeFi protocols (DeepBook, Bluefin, Cetus, Scallop, Aftermath, Navi, Turbos) to earn the highest available APY. Yield accrues to the pool and is distributed as a bonus to each cycle's winner. On the /ai page, you can see live APY data and AI-generated strategy recommendations.",

  "faq.q8": "Is Suivan non-custodial?",
  "faq.a8": "Yes. Suivan is fully non-custodial. You remain in control of your assets at all times through your wallet. Smart contracts handle pool logic and collateral on-chain. There is no admin key that can withdraw user funds. The protocol is designed with principle of least privilege — even the pool creator cannot access other participants' deposits.",

  "faq.q9": "What happens if someone defaults?",
  "faq.a9": "If a participant misses a payment, their collateral is slashed — the missed contribution amount is deducted and distributed to the pool. The remaining collateral stays locked until the end of the cycle. The pool continues normally; other members are protected. This is enforced entirely by smart contract, no human intervention needed.",

  "faq.q10": "Are the smart contracts audited?",
  "faq.a10": "The Suivan Move smart contracts are deployed on Sui testnet. The codebase is open-source and follows Sui Move security best practices: hot potato patterns for atomic operations, capability-based access control, and principle of least privilege. A full third-party audit is planned before mainnet launch.",

  "faq.q11": "How much does it cost to use Suivan?",
  "faq.a11": "Sui gas fees are extremely low — approximately 0.0001 SUI per transaction (less than $0.001). A full ROSCA cycle of 10 participants costs roughly 0.0011 SUI in total gas — effectively free. Compare this to Ethereum where the same operations would cost $15+. Use the /simulator to calculate your exact costs.",

  "faq.q12": "Can I create my own pool?",
  "faq.a12": "Absolutely. Connect your wallet, go to /pools, and click + Create Pool. You set the deposit amount, number of participants (2-50), and cycle duration (days or minutes for testing). You can optionally upload a custom name and description via Walrus for permanent decentralized storage. No approval needed — your pool is live immediately.",

  "faq.q13": "What is Walrus and how does Suivan use it?",
  "faq.a13": "Walrus is Sui's decentralized blob storage protocol. Suivan uses it to store pool metadata (names, descriptions) permanently on-chain rather than relying on centralized databases. This means your pool's identity is decentralized, immutable, and verifiable — just like the pool's financial state.",

  "faq.q14": "Where can I follow the project?",
  "faq.a14": "Join our community on Telegram (t.me/sui_van) and Discord (discord.gg/XxxM958bm). Follow @suivan_id on X/Twitter for updates. The codebase is open-source on GitHub. Suivan is a Sui Overflow 2026 hackathon project — we welcome feedback, contributors, and early testers.",
  "faq.q15": "How does the gacha jackpot work?",
  "faq.a15": "Every month, deposited contributions are deployed to earn yield via DeepBook V3 flash loan arbitrage and Sui DeFi protocols. The yield accumulates in a vault throughout the pool's lifetime. At the pool's end, all cumulative yield is distributed to ONE winner via weighted lottery (gacha). Your chance depends on your on-time payment score — each on-time payment earns leaderboard points, which convert to lottery tickets. The more tickets you hold, the higher your chance. Members who miss 2+ payments have their score reduced to zero and lose all gacha eligibility — the jackpot goes only to honest participants.",
  "faq.q16": "How is my leaderboard tier calculated?",
  "faq.a16": "Your tier is based on payment punctuality, yield earned, and number of pools joined. Paying between the 1st–10th earns the most points, 11th–15th earns medium, 16th–20th earns low, and after the 20th counts as late. Your cumulative points determine your tier: Bronze (0+), Silver (100+), Gold (200+), Platinum (300+), Diamond (400+). Higher tiers multiply your collateral yield at the pool's end. Points also determine your gacha tickets — but note: leaderboard points and gacha tickets are two separate reward systems.",

  "faq.contactTitle": "Still have questions?",
  "faq.contactDesc": "Join the Suivan community channels for updates, feedback, and collaboration.",

  "landing.badge": "Sui Overflow 2026",
  "landing.title": "Global ROSCA Pools.\nZero Gas. Real Yield.",
  "landing.subtitle": "Suivan brings Rotating Savings & Credit Associations (ROSCA) on-chain — a proven trillion-dollar informal finance model reimagined for DeFi. Deposit into your pool, let our AI engine deploy capital across the highest-yielding Sui protocols, and watch your returns compound automatically. No gas fees, no middlemen, no lock-ups. Just transparent, auditable smart contracts with zkLogin onboarding and sponsored transactions. Passive yield meets community trust — powered by Sui.",
  "landing.explore": "Explore Pools",
  "landing.how": "How It Works",
  "landing.statPools": "POOLS",
  "landing.statMembers": "MEMBERS",
  "landing.statVolume": "VOLUME",
  "landing.statApy": "AVG APY",
  "landing.whyBadge": "built_on_sui",
  "landing.whyTitle": "Powered by",
  "landing.whySui": "Sui",
  "landing.whyDesc": "Sui's object-centric model makes every ROSCA pool an inspectable on-chain entity. Combined with zkLogin, sponsored transactions, and Walrus blob storage, Suivan delivers a seamless community finance experience.",
  "landing.feature1Title": "zkLogin",
  "landing.feature1Desc": "Sign in with Google — no wallet, no seed phrase. Sui creates a wallet for you automatically.",
  "landing.feature2Title": "Sponsored Tx",
  "landing.feature2Desc": "Zero gas fees for first join. Suivan sponsors your transaction so you can start saving immediately.",
  "landing.feature3Title": "DeFi Yields",
  "landing.feature3Desc": "Idle pool funds routed to Cetus, NAVI, and Scallop — real APY from live Sui protocols.",
  "landing.feature4Title": "Walrus Storage",
  "landing.feature4Desc": "Pool metadata stored permanently on Walrus — decentralized, tamper-proof, always available.",
  "landing.step1Title": "Join with Google",
  "landing.step1Copy": "Sign in with zkLogin — no wallet, no seed phrase, no gas fees. Your Sui wallet is created automatically.",
  "landing.step2Title": "Pick a Pool",
  "landing.step2Copy": "Choose from open ROSCA circles. Review the terms, deposit collateral, and commit to the cycle.",
  "landing.step3Title": "Contribute Monthly",
  "landing.step3Copy": "Each cycle, deposit your share. Track your status: ready, pending, contributed, or paid out.",
  "landing.step4Title": "Earn Yield",
  "landing.step4Copy": "Idle pool funds earn DeFi yield automatically. AI-optimized strategies maximize returns across Sui protocols.",
  "landing.sectionTitle": "Community savings in four steps.",
  "landing.sectionSub": "From zero to yield — no crypto knowledge needed. Just Google login and a few clicks.",
  "landing.poolsBadge": "live_pools",
  "landing.poolsTitle": "Active ROSCA Circles",
  "landing.poolsDesc": "Browse real pools on Sui. Each pool is an inspectable on-chain object with transparent cycle state.",
  "landing.trustBadge": "security_layer",
  "landing.trustTitle": "Built for trust. Backed by Sui.",
  "landing.trustDesc": "Every contribution, payout, and cycle is recorded on Sui's ledger. Smart contracts enforce the rules. Collateral protects the group. Walrus makes pool data permanent and transparent.",
  "landing.trust1": "Non-Custodial",
  "landing.trust1Desc": "Funds remain in smart contracts — Suivan never holds your assets.",
  "landing.trust2": "Collateral-Backed",
  "landing.trust2Desc": "125% overcollateralization ensures commitment. Miss a payment? Collateral covers the group.",
  "landing.trust3": "Auditable",
  "landing.trust3Desc": "Every cycle, every payout, every yield event — fully transparent on Sui explorer.",
  "landing.ctaTitle": "Ready to save with your community?",
  "landing.ctaDesc": "Join a ROSCA pool, contribute monthly, and earn yield — all without a crypto wallet.",
  "landing.ctaButton": "Get Started Free",
  "landing.ctaBadge": "no_wallet_needed",
  "landing.cylinderDesc": "Top-tier {chain} lending protocol with real-time APY from DeFiLlama.",
  "landing.cylinderSupply": "Supply on {name} →",
  "landing.cylinderLive": "LIVE",
  "landing.cylinderSource": "SOURCE",
  "pools.title": "Explore ROSCA Pools",
  "pools.subtitle": "Discover rotating savings pools with visible cycle state, participant progress, and APY signals.",
  "pools.totalPools": "TOTAL POOLS",
  "pools.open": "OPEN",
  "pools.active": "ACTIVE", 
  "pools.usdc": "USDC",
  "pools.create": "+ Create Custom Pool",
  "pools.connectWallet": "Connect wallet to create pool",
  "pools.join": "Join Pool",
  "pools.viewDetails": "View Details",
  "pools.emptyTitle": "No pools found",
  "pools.emptyDesc": "No pools have been created yet. Be the first to create one!",
  "pools.emptyFilter": "There are no {filter} pools at the moment.",
  "pools.joinTitle": "Join {name}",
  "pools.deposit": "Cycle Deposit",
  "pools.collateral": "Required Collateral",
  "pools.collateralDesc": "125% of remaining deposits, returned at cycle end plus yield bonus",
  "pools.estimatedApy": "Estimated APY",
  "pools.coinLabel": "USDC Coin",
  "pools.agree": "By joining, you agree to make monthly deposits for {count} months",
  "pools.createTitle": "Create Custom Pool",
  "pools.totalValue": "Total Pool Value",
  "pools.poolDuration": "Pool Duration",
  "pools.requiredCollateral": "Required Collateral (125%)",

  "detail.back": "Back to Pools",
  "detail.poolInfo": "Pool Information",
  "detail.deposit": "DEPOSIT",
  "detail.members": "MEMBERS",
  "detail.cycle": "CYCLE",
  "detail.funds": "FUNDS",
  "detail.capacity": "Pool Capacity",
  "detail.yieldSection": "Yield and Cycle Signals",
  "detail.yield": "YIELD",
  "detail.estApy": "EST APY",
  "detail.collateral": "COLLATERAL",
  "detail.participants": "Participants ({count})",
  "detail.noParticipants": "No participants yet. Be the first to join!",
  "detail.yourStatus": "Your Status",
  "detail.activeParticipant": "Active Participant",
  "detail.youAreIn": "You are part of this ROSCA pool",
  "detail.collateralLocked": "Collateral Locked",
  "detail.totalDeposited": "Total Deposited",
  "detail.receivedPayout": "Received Payout",
  "detail.yes": "Yes",
  "detail.notYet": "Not yet",
  "detail.makeDeposit": "Make Cycle Deposit",
  "detail.collateralAvailable": "Collateral Available",
  "detail.collateralReturned": "Your collateral + yield bonus has been returned automatically when the pool ended.",
  "detail.notParticipant": "You are not a participant in this pool.",
  "detail.joinThisPool": "Join This Pool",
  "detail.yourWallet": "Your Wallet",
  "detail.usdcBalance": "USDC Balance",
  "detail.coinsAvailable": "{count} coin(s) available",
  "detail.getStarted": "Get Started",
  "detail.connectPrompt": "Connect your wallet to join this pool or view your status",
  "detail.chartDisclaimer": "Simulated projection based on current pool metrics. Real time-series data will appear after multiple cycles.",
  "ai.badge": "SUI YIELD EXPLORER",
  "ai.title": "SUI Yield Explorer",
  "ai.subtitle": "Live APY data from Sui DeFi protocols — deployed via DeepBook V3 flash loan arbitrage.",
  "ai.loading": "Fetching live yields...",
  "ai.errorTitle": "FETCH ERROR",
  "ai.avgApy": "AVG APY",
  "ai.maxApy": "MAX APY",
  "ai.protocols": "PROTOCOLS",
  "ai.totalTvl": "TOTAL TVL",
  "ai.protocolYields": "Protocol Yields",
  "ai.trend": "Trend",
  "ai.marketConditions": "Market Conditions",
  "ai.volatilityIndex": "Volatility Index",
  "ai.gasPrice": "Reference Gas Price",
  "ai.direction": "Direction",
  "ai.topProtocol": "Top",
  "ai.howSuivanUses": "How Suivan Deploys Yield",
  "ai.howSuivanUsesDesc": "Pool funds are automatically deployed to Sui DeFi protocols via DeepBook V3 flash loan arbitrage. All execution is automatic — no manual strategy selection needed. The optimal route is recalculated continuously.",
  "ai.step1Title": "Withdraw",
  "ai.step1Desc": "Pool funds withdrawn atomically via hot potato pattern — if any step fails, the entire transaction rolls back.",
  "ai.step2Title": "Arbitrage",
  "ai.step2Desc": "Flash loan borrowed from DeepBook → arbitrage executed across DEX and lending pools simultaneously.",
  "ai.step3Title": "Profit",
  "ai.step3Desc": "Profit deposited to yield_balance — accumulates for the gacha jackpot. Principal returned to pool.",
  "ai.step4Title": "Jackpot",
  "ai.step4Desc": "At pool end, one gacha winner takes all accumulated yield. Weighted by on-time payment score.",
  "ai.deepbookTitle": "DeepBook V3 — Live",
  "ai.deepbookMidPrice": "Mid Price",
  "ai.deepbookSpread": "Spread",
  "ai.deepbookBidDepth": "Bid Depth",
  "ai.deepbookAskDepth": "Ask Depth",
  "ai.deepbookLink": "View DeepBook Explorer",
  "ai.sortedBy": "Sorted by",
  "ai.howItWorks": "How Suivan Deploys Yield",
  "ai.autoNote": "All execution is automatic — no manual strategy required. Optimal routes are recalculated continuously via flash loan arbitrage.",
  "ai.seeDeepBookFlow": "See Full Flow",
  "ai.explorePools": "Explore Pools",
  "demo.badge": "demo_walkthrough",
  "demo.subtitle": "Five steps from zero to yield. No crypto knowledge needed.",
  "demo.step": "Step",
  "demo.step1Detail": "Sign in with Google via zkLogin. Suivan creates a Sui wallet for you automatically. No seed phrases, no browser extensions, no gas fees for first join.",
  "demo.step1Action": "Try Google Login",
  "demo.step2Detail": "Browse available pools (Small: 10 USDC, Medium: 50 USDC, Large: 100 USDC). Deposit collateral once — your commitment to the group. Sponsored transaction means you pay ZERO gas.",
  "demo.step2Action": "Sponsored Join",
  "demo.step3Detail": "Each cycle, deposit your share. Suivan tracks deposits per cycle — no double-deposit exploits. Miss a payment? Collateral is slashed proportionally.",
  "demo.step3Action": "Make Deposit",
  "demo.step4Detail": "One participant wins the pool each cycle. Selection uses on-chain entropy (tx digest + timestamp). Winner receives all cycle deposits + yield bonus.",
  "demo.step4Action": "Select Winner",
  "demo.step5Detail": "Idle pool funds are routed to Sui DeFi protocols (Cetus, NAVI, Scallop) for yield. APY signals from DeFiLlama — real data, real returns. After all cycles complete, collateral is returned.",
  "demo.step5Action": "View Yield Dashboard",
  "demo.feature1Title": "Zero Gas Fees",
  "demo.feature1Desc": "Sponsored transactions — join a pool without holding SUI.",
  "demo.feature2Title": "DeFi Yield",
  "demo.feature2Desc": "Idle funds routed to Sui protocols — real APY from DeFiLlama.",
  "demo.feature3Title": "On-Chain Metadata",
  "demo.feature3Desc": "Pool details stored on Walrus — permanent, decentralized.",
  "leaderboard.badge": "LEADERBOARD",
  "leaderboard.title": "Participant Rankings",
  "leaderboard.subtitle": "Ranked by payment punctuality, yield earned, and community reputation. Pay before the 20th to climb the tiers.",
  "leaderboard.statPools": "ACTIVE POOLS",
  "leaderboard.statUsers": "ALL TIME MEMBERS",
  "leaderboard.statEarned": "TOTAL YIELD DISTRIBUTED",
  "leaderboard.statAvgApy": "AVG APY",
  "leaderboard.tierDiamond": "Diamond",
  "leaderboard.tierPlatinum": "Platinum",
  "leaderboard.tierGold": "Gold",
  "leaderboard.tierSilver": "Silver",
  "leaderboard.tierBronze": "Bronze",
  "leaderboard.tierDesc": "Top-tier members with exceptional payment records and high yield accumulation.",
  "leaderboard.cycleTitle": "Current Cycle",
  "leaderboard.cycleDeadline": "Payment Deadline",
  "leaderboard.cycleDrawing": "Winner Drawing",
  "leaderboard.cyclePot": "Winner Pot",
  "leaderboard.yourRank": "Your Rank",
  "leaderboard.yourPoints": "Points",
  "leaderboard.yourYield": "Your Yield",
  "leaderboard.yourTier": "Your Tier",
  "leaderboard.notConnected": "Connect wallet to see your rank",
  "leaderboard.rank": "RANK",
  "leaderboard.member": "MEMBER",
  "leaderboard.tier": "TIER",
  "leaderboard.points": "POINTS",
  "leaderboard.payment": "PAYMENT",
  "leaderboard.yield": "YIELD",
  "leaderboard.onTime": "ON-TIME %",
  "leaderboard.pools": "POOLS",
  "leaderboard.early": "On Time",
  "leaderboard.late": "Late",
  "leaderboard.noData": "No participants yet. Join a pool to appear on the leaderboard.",
  "leaderboard.rulesTitle": "How Ranking Works",
  "leaderboard.rulesPayment": "Monthly Contribution",
  "leaderboard.rulesPaymentDesc": "Each member contributes monthly. Payment must be received by the 20th of every month. Late payments are deducted from collateral.",
  "leaderboard.rulesPoints": "Points System",
  "leaderboard.rulesPointsDesc": "Pay between 1st–10th: +100 pts | 11th–15th: +75 pts | 16th–20th: +50 pts | After 20th (late): +10 pts. Cumulative points determine your tier.",
  "leaderboard.rulesDrawing": "Winner Drawing",
  "leaderboard.rulesDrawingDesc": "Every 25th, one member is randomly selected to receive the total pot (participants × monthly contribution). All members remain in the cycle.",
  "leaderboard.rulesYield": "Yield Calculation",
  "leaderboard.rulesYieldDesc": "Two yields at cycle end: (1) Collateral Yield — base return × tier multiplier. (2) Cumulative Yield — pooled from all monthly contributions. Higher tier = bigger multiplier.",
  "leaderboard.rulesGacha": "Gacha Jackpot",
  "leaderboard.rulesGachaDesc": "All cumulative yield from monthly deposits is collected into a jackpot. At the pool's end, one winner is drawn via weighted lottery. Your on-time payment score determines how many tickets you get — the more consistent you are, the higher your chance. Members who miss 2+ payments lose all eligibility.",
  "leaderboard.cta": "Join a Pool",


  "simulator.badge": "SIMULATOR",
  "simulator.title": "How much wallet balance do you need?",
  "simulator.subtitle": "Calculate exactly how much USDC + SUI you need before joining a ROSCA pool. No surprises, no hidden costs.",
  "simulator.poolConfig": "Pool Configuration",
  "simulator.depositLabel": "Monthly Deposit (USDC)",
  "simulator.participantsLabel": "Number of Participants",
  "simulator.cycleLabel": "Cycle Duration (days)",
  "simulator.gasSponsor": "Sponsored Transactions",
  "simulator.gasSponsorDesc": "First join is free — sponsored by Suivan. Subsequent tx ~0.0001 SUI each.",
  "simulator.breakdown": "Wallet Requirement Breakdown",
  "simulator.totalUpfront": "Total Upfront Needed",
  "simulator.needToPrepare": "You need to prepare",
  "simulator.deposit": "Cycle Deposit",
  "simulator.collateral": "Collateral (125%)",
  "simulator.gas": "Gas Fee",
  "simulator.gasFree": "First join sponsored",
  "simulator.usdc": "USDC",
  "simulator.sui": "SUI",
  "simulator.poolSummary": "Pool Summary",
  "simulator.totalPool": "Total Pool Value",
  "simulator.totalCycles": "Total Cycles",
  "simulator.poolDuration": "Pool Duration",
  "simulator.yourPosition": "Your Position",
  "simulator.youPay": "You Pay Per Cycle",
  "simulator.youEarn": "You Earn Total",
  "simulator.compareTitle": "Ultra-low gas on Sui",
  "simulator.compareDesc": "Sui tx cost ~0.0001 SUI (fractions of a cent). Ethereum L1 averages ~$1.50 per tx.",
  "simulator.suiFee": "Sui Fee",
  "simulator.ethFee": "Ethereum Fee",
  "simulator.savings": "Efficiency",
  "simulator.cta": "Explore Real Pools",
  "simulator.collateralNote": "125% of remaining contribution commitment, returned at cycle end",
  "simulator.collateralDetail": "Collateral protects all members. If you miss a payment, the deposit is deducted from your collateral. Unused collateral + proportional yield is returned when the pool ends.",

  "faucet.badge": "TEST FAUCET",
  "faucet.title": "Get Test Tokens",
  "faucet.subtitle": "Step 1: Get free SUI for gas. Step 2: Claim 500 USDC for testing. Then explore Suivan pools before mainnet.",
  "faucet.claimUsdc": "Claim 10,000 Test USDC",
  "faucet.claimSui": "Claim 1 Test SUI",
  "faucet.walletRequired": "Connect your wallet to claim test tokens.",
  "faucet.success": "Tokens claimed successfully!",
  "faucet.error": "Faucet request failed",
  "faucet.cooldown": "Cooldown active. Try again in {time}s.",
  "faucet.description": "All tokens on this page are testnet-only \u2014 no real value. Use them to simulate pool creation, joining, and yield scenarios.",
  "faucet.usdcLabel": "USDC (Testnet)",
  "faucet.usdcDesc": "USDC stablecoin for pool deposits and collateral",
  "faucet.suiLabel": "TEST_SUI",
  "faucet.suiDesc": "SUI for gas fees (first tx is sponsored)",
  "faucet.recentTitle": "Recent Claims",
  "faucet.recentEmpty": "No claims yet. Start by connecting your wallet and minting tokens.",
  "faucet.balanceTitle": "Your Balances",
  "faucet.goToPools": "Go to Pools",

  "profile.badge": "YOUR DASHBOARD",
  "profile.title": "Your Profile",
  "profile.subtitle": "Track your pool memberships, NFT badges, and on-chain activity.",
  "profile.connectPrompt": "Connect your wallet to view your Suivan profile.",
  "profile.statsPools": "Pools Joined",
  "profile.statsWon": "Cycles Won",
  "profile.statsSaved": "Total Saved",
  "profile.statsYield": "Yield Earned",
  "profile.nftTitle": "Achievements",
  "profile.nftEmpty": "No achievements yet. Join a pool to earn your first Suivan achievement.",
  "profile.activityTitle": "Recent Activity",
  "profile.activityEmpty": "No recent activity. Your pool joins, cycle wins, and badge claims will appear here.",
  "profile.noActivity": "No activity yet. Join a pool to get started!",
  "profile.infoTitle": "Account Info",
  "profile.infoAddress": "Wallet Address",
  "profile.infoMemberSince": "Member Since",
  "profile.infoPools": "Active Pools",
  "profile.infoNetwork": "Network",
};

const id: Record<string, string> = {
  "nav.about": "ROSCA",
  "nav.howItWorks": "Cara Kerja",
  "nav.advantages": "Mengapa Sui",
  "nav.pools": "Pool",
  "nav.simulator": "Simulator",
  "nav.yield": "Yield Explorer",
  "nav.leaderboard": "Papan Peringkat",
  "nav.profile": "Profil",
  "nav.faq": "FAQ",
  "nav.faucet": "Faucet",
  "nav.demo": "Demo",
  "nav.yieldDemo": "Mesin Yield",
  "nav.connectWallet": "Hubungkan Dompet",

  "about.badge": "Apa itu Suivan?",
  "about.title": "Tabungan komunitas, dibangun ulang untuk",
  "about.titleHighlight": "Sui",
  "about.problemTitle": "Kekurangan ROSCA Tradisional",
  "about.problemSubtitle": "Masalah kepercayaan dan koordinasi",
  "about.problem1.title": "Risiko komitmen",
  "about.problem1.desc": "Anggota butuh insentif jelas untuk menyelesaikan setiap siklus.",
  "about.problem2.title": "Dana menganggur",
  "about.problem2.desc": "Modal bisa tidak terpakai di antara kontribusi dan pembayaran.",
  "about.problem3.title": "Catatan manual",
  "about.problem3.desc": "Status, giliran, dan pembayaran sulit diverifikasi secara luas.",
  "about.problem4.title": "Jangkauan terbatas",
  "about.problem4.desc": "Kelompok lokal butuh infrastruktur untuk berkoordinasi secara global.",
  "about.solutionTitle": "Arah Suivan",
  "about.solutionSubtitle": "Frontend komposable untuk pool ROSCA di Sui",
  "about.solution1.title": "Visibilitas jaminan",
  "about.solution1.desc": "Tampilkan status komitmen tanpa mengunci logika kontrak lama.",
  "about.solution2.title": "Sinyal yield",
  "about.solution2.desc": "Tampilkan APY dan peluang dana menganggur melalui batasan data modular.",
  "about.solution3.title": "Status siklus transparan",
  "about.solution3.desc": "Tampilkan progres partisipan, pembayaran, dan status kontribusi dengan jelas.",
  "about.solution4.title": "UX pool global",
  "about.solution4.desc": "Jelaskan Arisan sebagai ekspresi ROSCA lokal sambil menjaga produk tetap global.",
  "about.quote": "Kekayaan komunitas bekerja saat aturan terlihat, siklus jelas, dan anggota bisa berkoordinasi lintas batas.",
  "about.quoteBrand": "Suivan",
  "about.quoteEnd": "membuat antarmuka itu mudah dibaca.",
  "about.cta": "Lihat Cara Kerja",

  "faq.badge": "FAQ",
  "faq.title": "Pertanyaan Umum",
  "faq.subtitle": "Semua yang perlu kamu ketahui tentang Suivan, pool ROSCA, dan cara mulai menabung di Sui.",

  "faq.q1": "Apa itu Suivan?",
  "faq.a1": "Suivan adalah protokol ROSCA on-chain yang dibangun di Sui Move. Menghadirkan tabungan bergilir tradisional ke dalam DeFi — anggota komunitas berkontribusi bulanan, pemenang dipilih secara acak via Seal RNG, dan dana menganggur menghasilkan yield melalui strategi DeFi yang dioptimalkan AI. Tanpa bendahara, tanpa perantara, smart contract transparan penuh.",

  "faq.q2": "Apa itu ROSCA?",
  "faq.a2": "ROSCA (Rotating Savings and Credit Association) adalah model tabungan global yang dipraktikkan oleh miliaran orang — dikenal sebagai Arisan di Indonesia, Chit Fund di India, Tanda di Meksiko, dan banyak lagi. Anggota menyetor jumlah tetap setiap siklus. Setiap siklus, satu anggota menerima seluruh pembayaran yang terkumpul. Ini berulang sampai semua mendapat giliran.",

  "faq.q3": "Bagaimana cara mulai menggunakan Suivan?",
  "faq.a3": "Cukup hubungkan dompetmu — Suivan mendukung zkLogin, jadi kamu bisa masuk dengan Google atau penyedia OAuth apa pun, tanpa seed phrase. Buka /faucet untuk klaim SUI test gratis dan 500 USDC. Lalu jelajahi /pools, pilih yang sesuai anggaranmu, dan gabung. Gas transaksi pertamamu sangat rendah di Sui (~0,0001 SUI).",

  "faq.q4": "Kenapa Sui? Apa yang membuatnya berbeda?",
  "faq.a4": "Model object-centric Sui membuat setiap pool menjadi objek on-chain hidup yang bisa kamu periksa kapan saja. Finalitas sub-detik berarti penyelesaian instan. Biaya gas hanya pecahan sen (~Rp5). zkLogin menghilangkan kerumitan wallet. Seal RNG menyediakan pemilihan pemenang acak yang dapat diverifikasi. Walrus menyimpan metadata pool secara permanen. Stack ini mustahil di chain lain.",

  "faq.q5": "Bagaimana sistem jaminan bekerja?",
  "faq.a5": "Setiap peserta menyetor jaminan 125% di muka — dihitung sebagai 1,25 × (sisa kontribusi). Ini menjamin komitmen. Jika kamu melewatkan pembayaran, jaminanmu dipotong secara proporsional. Jika kamu menyelesaikan semua siklus dengan setia, jaminan penuh dikembalikan PLUS yield proporsional yang diperoleh selama masa pool. Ini menghilangkan risiko tradisional ROSCA di mana anggota kabur setelah mendapat giliran.",

  "faq.q6": "Bagaimana pemenang dipilih?",
  "faq.a6": "Pemenang dipilih secara acak setiap siklus menggunakan Seal RNG — generator angka acak on-chain asli Sui. Ini menjamin pemilihan yang adil, dapat diverifikasi, dan anti-manipulasi. Tanpa admin, tanpa undian manual, tanpa bias. Bukti keacakan tercatat on-chain untuk diverifikasi siapa pun.",

  "faq.q7": "Bagaimana yield bekerja?",
  "faq.a7": "Saat dana menganggur di antara siklus, AI Yield Optimizer kami menyebarkannya ke protokol DeFi Sui (DeepBook, Bluefin, Cetus, Scallop, Aftermath, Navi, Turbos) untuk mendapatkan APY tertinggi yang tersedia. Yield terkumpul ke pool dan didistribusikan sebagai bonus ke pemenang setiap siklus. Di halaman /ai, kamu bisa melihat data APY langsung dan rekomendasi strategi yang dihasilkan AI.",

  "faq.q8": "Apakah Suivan non-kustodial?",
  "faq.a8": "Ya. Suivan sepenuhnya non-kustodial. Kamu tetap memegang kendali penuh atas asetmu setiap saat melalui wallet-mu. Smart contract menangani logika pool dan jaminan on-chain. Tidak ada kunci admin yang bisa menarik dana pengguna. Protokol dirancang dengan prinsip hak istimewa terendah — bahkan pembuat pool tidak bisa mengakses deposit peserta lain.",

  "faq.q9": "Apa yang terjadi jika seseorang gagal bayar?",
  "faq.a9": "Jika seorang peserta melewatkan pembayaran, jaminannya dipotong — jumlah kontribusi yang terlewat dipotong dan didistribusikan ke pool. Sisa jaminan tetap terkunci hingga akhir siklus. Pool berlanjut normal; anggota lain terlindungi. Ini ditegakkan sepenuhnya oleh smart contract, tanpa perlu campur tangan manusia.",

  "faq.q10": "Apakah smart contract sudah diaudit?",
  "faq.a10": "Smart contract Suivan Move di-deploy di testnet Sui. Kode sumber bersifat open-source dan mengikuti praktik keamanan terbaik Sui Move: pola hot potato untuk operasi atomik, kontrol akses berbasis kapabilitas, dan prinsip hak istimewa terendah. Audit penuh pihak ketiga direncanakan sebelum peluncuran mainnet.",

  "faq.q11": "Berapa biaya menggunakan Suivan?",
  "faq.a11": "Biaya gas Sui sangat rendah — sekitar 0,0001 SUI per transaksi (kurang dari Rp5). Satu siklus ROSCA penuh dengan 10 peserta hanya menghabiskan sekitar 0,0011 SUI total gas — bisa dibilang gratis. Bandingkan dengan Ethereum di mana operasi yang sama akan menghabiskan $15+. Gunakan /simulator untuk menghitung biaya pastimu.",

  "faq.q12": "Bisakah saya membuat pool sendiri?",
  "faq.a12": "Tentu saja. Hubungkan wallet-mu, buka /pools, dan klik + Create Pool. Kamu mengatur jumlah setoran, jumlah peserta (2-50), dan durasi siklus (hari atau menit untuk testing). Kamu bisa mengunggah nama dan deskripsi kustom via Walrus untuk penyimpanan terdesentralisasi permanen. Tanpa perlu persetujuan — pool-mu langsung aktif.",

  "faq.q13": "Apa itu Walrus dan bagaimana Suivan menggunakannya?",
  "faq.a13": "Walrus adalah protokol penyimpanan blob terdesentralisasi dari Sui. Suivan menggunakannya untuk menyimpan metadata pool (nama, deskripsi) secara permanen on-chain daripada bergantung pada database terpusat. Ini berarti identitas pool-mu terdesentralisasi, tidak dapat diubah, dan dapat diverifikasi — sama seperti status keuangan pool.",

  "faq.q14": "Di mana saya bisa mengikuti proyek ini?",
  "faq.a14": "Gabung komunitas kami di Telegram (t.me/sui_van) dan Discord (discord.gg/XxxM958bm). Ikuti @suivan_id di X/Twitter untuk update. Kode sumber open-source di GitHub. Suivan adalah proyek hackathon Sui Overflow 2026 — kami menyambut masukan, kontributor, dan penguji awal.",
  "faq.q15": "Bagaimana cara kerja jackpot gacha?",
  "faq.a15": "Setiap bulan, iuran yang disetor dideploy untuk menghasilkan yield melalui arbitrase flash loan DeepBook V3 dan protokol DeFi Sui. Yield terkumpul di vault selama masa pool. Di akhir pool, semua yield kumulatif dibagikan ke SATU pemenang via lotere berbobot (gacha). Peluang Anda bergantung pada skor pembayaran tepat waktu — setiap pembayaran tepat waktu menghasilkan poin leaderboard, yang dikonversi menjadi tiket lotere. Semakin banyak tiket, semakin tinggi peluang. Anggota yang melewatkan 2+ pembayaran skornya menjadi nol dan kehilangan semua eligibilitas gacha — jackpot hanya untuk peserta jujur.",
  "faq.q16": "Bagaimana tingkat (tier) leaderboard saya dihitung?",
  "faq.a16": "Tingkat Anda berdasarkan ketepatan pembayaran, yield yang dihasilkan, dan jumlah pool yang diikuti. Membayar antara tanggal 1–10 mendapat poin terbanyak, 11–15 menengah, 16–20 rendah, setelah tanggal 20 dianggap terlambat. Poin kumulatif menentukan tingkat: Bronze (0+), Silver (100+), Gold (200+), Platinum (300+), Diamond (400+). Tingkat lebih tinggi melipatgandakan yield collateral di akhir pool. Poin juga menentukan tiket gacha — namun perlu dicatat: poin leaderboard dan tiket gacha adalah dua sistem reward terpisah.",

  "faq.contactTitle": "Masih ada pertanyaan?",
  "faq.contactDesc": "Bergabunglah dengan saluran komunitas Suivan untuk pembaruan, umpan balik, dan kolaborasi.",

  "landing.badge": "Sui Overflow 2026",
  "landing.title": "Pool ROSCA Global.\nNol Gas. Yield Nyata.",
  "landing.subtitle": "Suivan menghadirkan Rotating Savings & Credit Associations (ROSCA) di on-chain — model keuangan informal triliunan dolar yang kini direvolusi di DeFi. Setorkan dana ke pool Anda, biarkan mesin AI kami mengalokasikan modal ke protokol Sui dengan yield tertinggi, dan saksikan return Anda tumbuh secara otomatis. Tanpa gas fee, tanpa perantara, tanpa lock-up. Hanya smart contract yang transparan dan teraudit, dengan onboarding zkLogin serta transaksi disponsori. Yield pasif bertemu kepercayaan komunitas — ditenagai oleh Sui.",
  "landing.explore": "Jelajahi Pool",
  "landing.how": "Cara Kerja",
  "landing.statPools": "POOL",
  "landing.statMembers": "ANGGOTA",
  "landing.statVolume": "VOLUME",
  "landing.statApy": "RATA APY",
  "landing.whyBadge": "dibangun_di_sui",
  "landing.whyTitle": "Ditenagai oleh",
  "landing.whySui": "Sui",
  "landing.whyDesc": "Model object-centric Sui membuat setiap pool ROSCA menjadi entitas on-chain yang dapat diperiksa. Dengan zkLogin, transaksi disponsori, dan penyimpanan Walrus, Suivan menghadirkan pengalaman keuangan komunitas yang mulus.",
  "landing.feature1Title": "zkLogin",
  "landing.feature1Desc": "Masuk dengan Google — tanpa dompet, tanpa seed phrase. Sui membuat dompet untuk Anda secara otomatis.",
  "landing.feature2Title": "Tx Sponsored",
  "landing.feature2Desc": "Biaya gas nol untuk gabung pertama. Suivan mensponsori transaksi Anda sehingga Anda bisa mulai menabung segera.",
  "landing.feature3Title": "Yield DeFi",
  "landing.feature3Desc": "Dana idle pool dialihkan ke Cetus, NAVI, dan Scallop — APY nyata dari protokol Sui langsung.",
  "landing.feature4Title": "Penyimpanan Walrus",
  "landing.feature4Desc": "Metadata pool disimpan permanen di Walrus — terdesentralisasi, anti-rusak, selalu tersedia.",
  "landing.step1Title": "Gabung dengan Google",
  "landing.step1Copy": "Masuk dengan zkLogin — tanpa dompet, tanpa seed phrase, tanpa biaya gas. Dompet Sui Anda dibuat otomatis.",
  "landing.step2Title": "Pilih Pool",
  "landing.step2Copy": "Pilih dari lingkaran ROSCA yang tersedia. Tinjau ketentuan, setor jaminan, dan komit ke siklus.",
  "landing.step3Title": "Kontribusi Bulanan",
  "landing.step3Copy": "Setiap siklus, setorkan bagian Anda. Lacak status: siap, tertunda, terkontribusi, atau terbayar.",
  "landing.step4Title": "Hasilkan Yield",
  "landing.step4Copy": "Dana idle pool menghasilkan yield DeFi secara otomatis. Strategi yang dioptimalkan AI memaksimalkan hasil di seluruh protokol Sui.",
  "landing.sectionTitle": "Tabungan komunitas dalam empat langkah.",
  "landing.sectionSub": "Dari nol hingga yield — tanpa perlu pengetahuan kripto. Cukup login Google dan beberapa klik.",
  "landing.poolsBadge": "pool_langsung",
  "landing.poolsTitle": "Lingkaran ROSCA Aktif",
  "landing.poolsDesc": "Jelajahi pool nyata di Sui. Setiap pool adalah objek on-chain yang dapat diperiksa dengan status siklus transparan.",
  "landing.trustBadge": "lapisan_keamanan",
  "landing.trustTitle": "Dibangun untuk kepercayaan. Didukung Sui.",
  "landing.trustDesc": "Setiap kontribusi, pembayaran, dan siklus dicatat di ledger Sui. Kontrak pintar menegakkan aturan. Jaminan melindungi grup. Walrus membuat data pool permanen dan transparan.",
  "landing.trust1": "Non-Kustodial",
  "landing.trust1Desc": "Dana tetap di kontrak pintar — Suivan tidak pernah memegang aset Anda.",
  "landing.trust2": "Dijamin",
  "landing.trust2Desc": "Overcollateralization 125% memastikan komitmen. Tidak bayar? Jaminan menutupi grup.",
  "landing.trust3": "Dapat Diaudit",
  "landing.trust3Desc": "Setiap siklus, setiap pembayaran, setiap event yield — transparan penuh di Sui explorer.",
  "landing.ctaTitle": "Siap menabung dengan komunitas Anda?",
  "landing.ctaDesc": "Gabung pool ROSCA, kontribusi bulanan, dan hasilkan yield — semua tanpa dompet kripto.",
  "landing.ctaButton": "Mulai Gratis",
  "landing.ctaBadge": "tanpa_dompet",
  "landing.cylinderDesc": "Protokol pinjaman {chain} kelas atas dengan APY real-time dari DeFiLlama.",
  "landing.cylinderSupply": "Supply di {name} →",
  "landing.cylinderLive": "LIVE",
  "landing.cylinderSource": "SUMBER",
  "pools.title": "Jelajahi Pool ROSCA",
  "pools.subtitle": "Temukan pool tabungan bergilir dengan status siklus yang terlihat, progres peserta, dan sinyal APY.",
  "pools.totalPools": "TOTAL POOL",
  "pools.open": "TERBUKA",
  "pools.active": "AKTIF",
  "pools.usdc": "USDC",
  "pools.create": "+ Buat Pool Kustom",
  "pools.connectWallet": "Hubungkan dompet untuk membuat pool",
  "pools.join": "Gabung Pool",
  "pools.viewDetails": "Lihat Detail",
  "pools.emptyTitle": "Tidak ada pool ditemukan",
  "pools.emptyDesc": "Belum ada pool yang dibuat. Jadilah yang pertama!",
  "pools.emptyFilter": "Tidak ada pool {filter} saat ini.",
  "pools.joinTitle": "Gabung {name}",
  "pools.deposit": "Setoran per Siklus",
  "pools.collateral": "Jaminan Diperlukan",
  "pools.collateralDesc": "125% dari sisa setoran, dikembalikan di akhir siklus ditambah bonus yield",
  "pools.estimatedApy": "Estimasi APY",
  "pools.coinLabel": "Koin USDC",
  "pools.agree": "Dengan bergabung, Anda setuju untuk melakukan setoran bulanan selama {count} bulan",
  "pools.createTitle": "Buat Pool Kustom",
  "pools.totalValue": "Total Nilai Pool",
  "pools.poolDuration": "Durasi Pool",
  "pools.requiredCollateral": "Jaminan Diperlukan (125%)",

  "detail.back": "Kembali ke Pool",
  "detail.poolInfo": "Informasi Pool",
  "detail.deposit": "SETORAN",
  "detail.members": "ANGGOTA",
  "detail.cycle": "SIKLUS",
  "detail.funds": "DANA",
  "detail.capacity": "Kapasitas Pool",
  "detail.yieldSection": "Sinyal Yield dan Siklus",
  "detail.yield": "YIELD",
  "detail.estApy": "EST APY",
  "detail.collateral": "JAMINAN",
  "detail.participants": "Peserta ({count})",
  "detail.noParticipants": "Belum ada peserta. Jadilah yang pertama!",
  "detail.yourStatus": "Status Anda",
  "detail.activeParticipant": "Peserta Aktif",
  "detail.youAreIn": "Anda adalah bagian dari pool ROSCA ini",
  "detail.collateralLocked": "Jaminan Terkunci",
  "detail.totalDeposited": "Total Disetor",
  "detail.receivedPayout": "Sudah Dibayar",
  "detail.yes": "Ya",
  "detail.notYet": "Belum",
  "detail.makeDeposit": "Lakukan Setoran Siklus",
  "detail.collateralAvailable": "Jaminan Tersedia",
  "detail.collateralReturned": "Jaminan + bonus yield Anda telah dikembalikan secara otomatis saat pool berakhir.",
  "detail.notParticipant": "Anda bukan peserta di pool ini.",
  "detail.joinThisPool": "Gabung Pool Ini",
  "detail.yourWallet": "Dompet Anda",
  "detail.usdcBalance": "Saldo USDC",
  "detail.coinsAvailable": "{count} koin tersedia",
  "detail.getStarted": "Mulai",
  "detail.connectPrompt": "Hubungkan dompet Anda untuk bergabung dengan pool ini atau lihat status Anda",
  "detail.chartDisclaimer": "Proyeksi simulasi berdasarkan metrik pool saat ini. Data deret waktu nyata akan muncul setelah beberapa siklus.",
  "ai.badge": "SUI YIELD EXPLORER",
  "ai.title": "SUI Yield Explorer",
  "ai.subtitle": "Data APY langsung dari protokol Sui DeFi — dideploy via arbitrase flash loan DeepBook V3.",
  "ai.loading": "Mengambil data yield...",
  "ai.errorTitle": "KESALAHAN",
  "ai.avgApy": "RATA-RATA APY",
  "ai.maxApy": "APY MAKS",
  "ai.protocols": "PROTOKOL",
  "ai.totalTvl": "TOTAL TVL",
  "ai.protocolYields": "Yield Protokol",
  "ai.trend": "Tren",
  "ai.marketConditions": "Kondisi Pasar",
  "ai.volatilityIndex": "Indeks Volatilitas",
  "ai.gasPrice": "Harga Referensi Gas",
  "ai.direction": "Arah",
  "ai.topProtocol": "Teratas",
  "ai.howSuivanUses": "Bagaimana Suivan Mendeploy Yield",
  "ai.howSuivanUsesDesc": "Dana pool otomatis dideploy ke protokol Sui DeFi via arbitrase flash loan DeepBook V3. Semua eksekusi otomatis — tidak perlu pilih strategi manual. Rute optimal dikalkulasi ulang secara terus-menerus.",
  "ai.step1Title": "Tarik Dana",
  "ai.step1Desc": "Dana pool ditarik secara atomik via hot potato pattern — jika gagal, seluruh transaksi di-rollback.",
  "ai.step2Title": "Arbitrase",
  "ai.step2Desc": "Flash loan dipinjam dari DeepBook → arbitrase dieksekusi di DEX dan lending pool secara bersamaan.",
  "ai.step3Title": "Profit",
  "ai.step3Desc": "Profit disetor ke yield_balance — terkumpul untuk jackpot gacha. Principal dikembalikan ke pool.",
  "ai.step4Title": "Jackpot",
  "ai.step4Desc": "Di akhir pool, satu pemenang gacha mengambil semua yield. Bobot ditentukan oleh skor pembayaran tepat waktu.",
  "ai.deepbookTitle": "DeepBook V3 — Live",
  "ai.deepbookMidPrice": "Harga Tengah",
  "ai.deepbookSpread": "Spread",
  "ai.deepbookBidDepth": "Kedalaman Bid",
  "ai.deepbookAskDepth": "Kedalaman Ask",
  "ai.deepbookLink": "Lihat DeepBook Explorer",
  "ai.sortedBy": "Diurutkan dari",
  "ai.howItWorks": "Bagaimana Suivan Mendeploy Yield",
  "ai.autoNote": "Semua eksekusi otomatis — tidak perlu strategi manual. Rute optimal dikalkulasi ulang secara terus-menerus via arbitrase flash loan.",
  "ai.seeDeepBookFlow": "Lihat Alur Lengkap",
  "ai.explorePools": "Jelajahi Pool",
  "demo.badge": "panduan_demo",
  "demo.subtitle": "Lima langkah dari nol hingga yield. Tidak perlu pengetahuan kripto.",
  "demo.step": "Langkah",
  "demo.step1Detail": "Masuk dengan Google via zkLogin. Suivan membuat dompet Sui secara otomatis. Tanpa seed phrase, tanpa ekstensi browser, tanpa biaya gas untuk bergabung pertama.",
  "demo.step1Action": "Coba Login Google",
  "demo.step2Detail": "Jelajahi pool yang tersedia (Kecil: 10 USDC, Sedang: 50 USDC, Besar: 100 USDC). Setor jaminan sekali — komitmen Anda ke grup. Transaksi disponsori berarti Anda membayar NOL gas.",
  "demo.step2Action": "Gabung Sponsored",
  "demo.step3Detail": "Setiap siklus, setorkan bagian Anda. Suivan melacak setoran per siklus — tidak ada eksploitasi setoran ganda. Tidak bayar? Jaminan dipotong secara proporsional.",
  "demo.step3Action": "Lakukan Setoran",
  "demo.step4Detail": "Satu peserta memenangkan pool setiap siklus. Seleksi menggunakan entropi on-chain (tx digest + timestamp). Pemenang menerima semua setoran siklus + bonus yield.",
  "demo.step4Action": "Pilih Pemenang",
  "demo.step5Detail": "Dana idle pool dialihkan ke protokol DeFi Sui (Cetus, NAVI, Scallop) untuk yield. Sinyal APY dari DeFiLlama — data nyata, hasil nyata. Setelah semua siklus selesai, jaminan dikembalikan.",
  "demo.step5Action": "Lihat Dashboard Yield",
  "demo.feature1Title": "Biaya Gas Nol",
  "demo.feature1Desc": "Transaksi disponsori — gabung pool tanpa memiliki SUI.",
  "demo.feature2Title": "Yield DeFi",
  "demo.feature2Desc": "Dana idle dialihkan ke protokol Sui — APY nyata dari DeFiLlama.",
  "demo.feature3Title": "Metadata On-Chain",
  "demo.feature3Desc": "Detail pool disimpan di Walrus — permanen, terdesentralisasi.",
  "leaderboard.badge": "LEADERBOARD",
  "leaderboard.title": "Peringkat Peserta",
  "leaderboard.subtitle": "Peringkat berdasarkan ketepatan pembayaran, yield, dan reputasi komunitas. Bayar sebelum tanggal 20 untuk naik peringkat.",
  "leaderboard.statPools": "POOL AKTIF",
  "leaderboard.statUsers": "ANGGOTA",
  "leaderboard.statEarned": "TOTAL YIELD",
  "leaderboard.statAvgApy": "RATA APY",
  "leaderboard.tierDiamond": "Berlian",
  "leaderboard.tierPlatinum": "Platinum",
  "leaderboard.tierGold": "Emas",
  "leaderboard.tierSilver": "Perak",
  "leaderboard.tierBronze": "Perunggu",
  "leaderboard.tierDesc": "Anggota dengan rekor pembayaran luar biasa dan akumulasi yield tinggi.",
  "leaderboard.cycleTitle": "Siklus Saat Ini",
  "leaderboard.cycleDeadline": "Batas Pembayaran",
  "leaderboard.cycleDrawing": "Pengundian Pemenang",
  "leaderboard.cyclePot": "Hadiah Pemenang",
  "leaderboard.yourRank": "Peringkat Anda",
  "leaderboard.yourPoints": "Poin",
  "leaderboard.yourYield": "Yield Anda",
  "leaderboard.yourTier": "Tingkat Anda",
  "leaderboard.notConnected": "Hubungkan dompet untuk melihat peringkat",
  "leaderboard.rank": "PERINGKAT",
  "leaderboard.member": "ANGGOTA",
  "leaderboard.tier": "TINGKAT",
  "leaderboard.points": "POIN",
  "leaderboard.payment": "PEMBAYARAN",
  "leaderboard.yield": "YIELD",
  "leaderboard.onTime": "TEPAT WAKTU",
  "leaderboard.pools": "POOL",
  "leaderboard.early": "Tepat Waktu",
  "leaderboard.late": "Terlambat",
  "leaderboard.noData": "Belum ada peserta. Gabung pool untuk muncul di papan peringkat.",
  "leaderboard.rulesTitle": "Cara Peringkat Bekerja",
  "leaderboard.rulesPayment": "Iuran Bulanan",
  "leaderboard.rulesPaymentDesc": "Setiap anggota membayar iuran bulanan. Pembayaran harus diterima sebelum tanggal 20. Pembayaran terlambat dipotong dari collateral.",
  "leaderboard.rulesPoints": "Sistem Poin",
  "leaderboard.rulesPointsDesc": "Bayar 1–10: +100 pts | 11–15: +75 pts | 16–20: +50 pts | Setelah 20 (telat): +10 pts. Poin kumulatif menentukan tingkat Anda.",
  "leaderboard.rulesDrawing": "Pengundian Pemenang",
  "leaderboard.rulesDrawingDesc": "Setiap tanggal 25, satu anggota dipilih secara acak untuk menerima total pot (peserta × iuran bulanan). Semua anggota tetap dalam siklus.",
  "leaderboard.rulesYield": "Perhitungan Yield",
  "leaderboard.rulesYieldDesc": "Dua yield di akhir siklus: (1) Yield Collateral — hasil dasar × pengali tingkat. (2) Yield Kumulatif — dikumpulkan dari semua iuran bulanan. Tingkat lebih tinggi = pengali lebih besar.",
  "leaderboard.rulesGacha": "Jackpot Gacha",
  "leaderboard.rulesGachaDesc": "Semua yield kumulatif dari iuran bulanan dikumpulkan menjadi jackpot. Di akhir pool, satu pemenang diundi via lotere berbobot. Skor pembayaran tepat waktu menentukan jumlah tiket Anda — semakin konsisten, semakin tinggi peluang. Anggota yang melewatkan 2+ pembayaran kehilangan semua eligibilitas gacha.",
  "leaderboard.cta": "Gabung Pool",


  "simulator.badge": "SIMULATOR",
  "simulator.title": "Berapa saldo dompet yang dibutuhkan?",
  "simulator.subtitle": "Hitung persis berapa USDC + SUI yang Anda perlukan sebelum bergabung dengan pool ROSCA. Tanpa kejutan, tanpa biaya tersembunyi.",
  "simulator.poolConfig": "Konfigurasi Pool",
  "simulator.depositLabel": "Setoran per Siklus (USDC)",
  "simulator.participantsLabel": "Jumlah Peserta",
  "simulator.cycleLabel": "Durasi Siklus (hari)",
  "simulator.gasSponsor": "Transaksi Disponsori",
  "simulator.gasSponsorDesc": "Gabung pertama gratis — disponsori Suivan. Tx berikutnya ~0,0001 SUI per transaksi.",
  "simulator.breakdown": "Rincian Kebutuhan Dompet",
  "simulator.totalUpfront": "Total Dana Dibutuhkan",
  "simulator.needToPrepare": "Anda perlu menyiapkan",
  "simulator.deposit": "Setoran Siklus",
  "simulator.collateral": "Jaminan (125%)",
  "simulator.gas": "Biaya Gas",
  "simulator.gasFree": "Gabung pertama disponsori",
  "simulator.usdc": "USDC",
  "simulator.sui": "SUI",
  "simulator.poolSummary": "Ringkasan Pool",
  "simulator.totalPool": "Total Nilai Pool",
  "simulator.totalCycles": "Total Siklus",
  "simulator.poolDuration": "Durasi Pool",
  "simulator.yourPosition": "Posisi Anda",
  "simulator.youPay": "Bayar Per Siklus",
  "simulator.youEarn": "Total yang Anda Terima",
  "simulator.compareTitle": "Gas ultra-rendah di Sui",
  "simulator.compareDesc": "Biaya tx Sui ~0,0001 SUI (pecahan sen). Ethereum L1 rata-rata ~$1,50 per tx.",
  "simulator.suiFee": "Biaya Sui",
  "simulator.ethFee": "Biaya Ethereum",
  "simulator.savings": "Efisiensi",
  "simulator.cta": "Jelajahi Pool Nyata",
  "simulator.collateralNote": "125% dari sisa komitmen kontribusi, dikembalikan di akhir siklus",
  "simulator.collateralDetail": "Jaminan melindungi semua anggota. Jika kamu melewatkan pembayaran, setoran dipotong dari jaminan. Jaminan yang tidak digunakan + yield proporsional dikembalikan saat pool berakhir.",

  "faucet.badge": "FAUCET TEST",
  "faucet.title": "Dapatkan Token Tes",
  "faucet.subtitle": "Langkah 1: Dapatkan SUI gratis untuk gas. Langkah 2: Klaim 500 USDC untuk testing. Lalu jelajahi pool Suivan sebelum mainnet.",
  "faucet.claimUsdc": "Klaim 10,000 Test USDC",
  "faucet.claimSui": "Klaim 1 Test SUI",
  "faucet.walletRequired": "Hubungkan dompet Anda untuk klaim token tes.",
  "faucet.success": "Token berhasil diklaim!",
  "faucet.error": "Permintaan faucet gagal",
  "faucet.cooldown": "Cooldown aktif. Coba lagi dalam {time}s.",
  "faucet.description": "Semua token di halaman ini hanya testnet \u2014 tidak bernilai riil. Gunakan untuk simulasi pembuatan pool, join, dan yield.",
  "faucet.usdcLabel": "USDC (Testnet)",
  "faucet.usdcDesc": "Stablecoin USDC untuk deposit dan jaminan pool",
  "faucet.suiLabel": "TEST_SUI",
  "faucet.suiDesc": "SUI untuk biaya gas (transaksi pertama gratis)",
  "faucet.recentTitle": "Klaim Terbaru",
  "faucet.recentEmpty": "Belum ada klaim. Mulai dengan menghubungkan dompet Anda.",
  "faucet.balanceTitle": "Saldo Anda",
  "faucet.goToPools": "Ke Pools",

  "profile.badge": "DASHBOARD ANDA",
  "profile.title": "Profil Anda",
  "profile.subtitle": "Pantau keanggotaan pool, lencana NFT, dan aktivitas on-chain Anda.",
  "profile.connectPrompt": "Hubungkan dompet Anda untuk melihat profil Suivan.",
  "profile.statsPools": "Pool Diikuti",
  "profile.statsWon": "Siklus Menang",
  "profile.statsSaved": "Total Ditabung",
  "profile.statsYield": "Yield Didapat",
  "profile.nftTitle": "Pencapaian",
  "profile.nftEmpty": "Belum ada pencapaian. Gabung pool untuk dapatkan pencapaian Suivan pertama Anda.",
  "profile.activityTitle": "Aktivitas Terbaru",
  "profile.activityEmpty": "Belum ada aktivitas. Join pool, menang siklus, dan klaim badge akan muncul di sini.",
  "profile.noActivity": "Belum ada aktivitas. Gabung pool untuk memulai!",
  "profile.infoTitle": "Info Akun",
  "profile.infoAddress": "Alamat Dompet",
  "profile.infoMemberSince": "Anggota Sejak",
  "profile.infoPools": "Pool Aktif",
  "profile.infoNetwork": "Jaringan",
};

const translations: Record<Language, Record<string, string>> = { en, id };

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const stored = localStorage.getItem("suivan-language") as Language | null;
    return stored === "en" || stored === "id" ? stored : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("suivan-language", lang);
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language]?.[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t } as LanguageContextType}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
