"use client";

import { createContext, ReactNode, useContext, useState } from "react";

export type Language = "en" | "id";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const en: Record<string, string> = {
  "nav.about": "ROSCA",
  "nav.howItWorks": "How It Works",
  "nav.advantages": "Why Sui",
  "nav.pools": "Pools",
  "nav.faq": "FAQ",
  "nav.yield": "Yield Explorer",

  "ai.badge": "SUI YIELD EXPLORER",
  "ai.title": "SUI Yield Explorer",
  "ai.subtitle": "Live APY data from Sui DeFi protocols — deployed via DeepBook V3 flash loan arbitrage.",
  "ai.loading": "Fetching live yields...",
  "ai.errorTitle": "FETCH ERROR",
  "ai.avgApy": "AVG APY",
  "ai.maxApy": "MAX APY",
  "ai.protocols": "PROTOCOLS",
  "ai.totalTvl": "TOTAL TVL",
  "ai.protocolYields": "Protocol Yields",
  "ai.trend": "Trend",
  "ai.marketConditions": "Market Conditions",
  "ai.volatilityIndex": "Volatility Index",
  "ai.gasPrice": "Reference Gas Price",
  "ai.direction": "Direction",
  "ai.topProtocol": "Top",
  "ai.howSuivanUses": "How Suivan Deploys Yield",
  "ai.howSuivanUsesDesc": "Pool funds are automatically deployed to Sui DeFi protocols via DeepBook V3 flash loan arbitrage. All execution is automatic — no manual strategy selection needed. The optimal route is recalculated continuously.",
  "ai.step1Title": "Withdraw",
  "ai.step1Desc": "Pool funds withdrawn atomically via hot potato pattern — if any step fails, the entire transaction rolls back.",
  "ai.step2Title": "Arbitrage",
  "ai.step2Desc": "Flash loan borrowed from DeepBook → arbitrage executed across DEX and lending pools simultaneously.",
  "ai.step3Title": "Profit",
  "ai.step3Desc": "Profit deposited to yield_balance — accumulates for the gacha jackpot. Principal returned to pool.",
  "ai.step4Title": "Jackpot",
  "ai.step4Desc": "At pool end, one gacha winner takes all accumulated yield. Weighted by on-time payment score.",
  "ai.deepbookTitle": "DeepBook V3 — Live",
  "ai.deepbookMidPrice": "Mid Price",
  "ai.deepbookSpread": "Spread",
  "ai.deepbookBidDepth": "Bid Depth",
  "ai.deepbookAskDepth": "Ask Depth",
  "ai.deepbookLink": "View DeepBook Explorer",
  "ai.explorePools": "Explore Pools",
  "ai.sortedBy": "Sorted by",
  "ai.howItWorks": "How Suivan Deploys Yield",
  "ai.autoNote": "All execution is automatic — no manual strategy required. Optimal routes are recalculated continuously via flash loan arbitrage.",
  "ai.seeDeepBookFlow": "See Full Flow",

  "nav.simulator": "Simulator",

  "simulator.badge": "SIMULATOR",
  "simulator.title": "How much wallet balance do you need?",
  "simulator.subtitle": "Calculate exactly how much USDC + SUI you need before joining a ROSCA pool. No surprises, no hidden costs.",
  "simulator.poolConfig": "Pool Configuration",
  "simulator.depositLabel": "Monthly Deposit (USDC)",
  "simulator.participantsLabel": "Number of Participants",
  "simulator.cycleLabel": "Cycle Duration (days)",
  "simulator.gasSponsor": "Sponsored Transactions",
  "simulator.gasSponsorDesc": "First join is free — sponsored by Suivan. Subsequent tx ~0.0001 SUI each.",
  "simulator.breakdown": "Wallet Requirement Breakdown",
  "simulator.totalUpfront": "Total Upfront Needed",
  "simulator.needToPrepare": "You need to prepare",
  "simulator.deposit": "Cycle Deposit",
  "simulator.collateral": "Collateral (125%)",
  "simulator.gas": "Gas Fee",
  "simulator.gasFree": "First join sponsored",
  "simulator.usdc": "USDC",
  "simulator.sui": "SUI",
  "simulator.poolSummary": "Pool Summary",
  "simulator.totalPool": "Total Pool Value",
  "simulator.totalCycles": "Total Cycles",
  "simulator.poolDuration": "Pool Duration",
  "simulator.yourPosition": "Your Position",
  "simulator.youPay": "You Pay Per Cycle",
  "simulator.youEarn": "You Earn Total",
  "simulator.compareTitle": "Ultra-low gas on Sui",
  "simulator.compareDesc": "Sui tx cost ~0.0001 SUI (fractions of a cent). Ethereum L1 averages ~$1.50 per tx.",
  "simulator.suiFee": "Sui Fee",
  "simulator.ethFee": "Ethereum Fee",
  "simulator.savings": "Efficiency",
  "simulator.cta": "Explore Real Pools",
  "simulator.collateralNote": "125% of remaining contribution commitment, returned at cycle end",
  "simulator.collateralDetail": "Collateral protects all members. If you miss a payment, the deposit is deducted from your collateral. Unused collateral + proportional yield is returned when the pool ends.",

  "faucet.badge": "TEST FAUCET",
  "faucet.title": "Get Test Tokens",
  "faucet.subtitle": "Step 1: Get free SUI for gas. Step 2: Claim 500 USDC for testing. Then explore Suivan pools before mainnet.",
  "faucet.claimUsdc": "Claim 10,000 Test USDC",
  "faucet.claimSui": "Claim 1 Test SUI",
  "faucet.walletRequired": "Connect your wallet to claim test tokens.",
  "faucet.success": "Tokens claimed successfully!",
  "faucet.error": "Faucet request failed",
  "faucet.cooldown": "Cooldown active. Try again in {time}s.",
  "faucet.description": "All tokens on this page are testnet-only \u2014 no real value. Use them to simulate pool creation, joining, and yield scenarios.",
  "faucet.usdcLabel": "USDC (Testnet)",
  "faucet.usdcDesc": "USDC stablecoin for pool deposits and collateral",
  "faucet.suiLabel": "TEST_SUI",
  "faucet.suiDesc": "SUI for gas fees (first tx is sponsored)",
  "faucet.recentTitle": "Recent Claims",
  "faucet.recentEmpty": "No claims yet. Start by connecting your wallet and minting tokens.",
  "faucet.balanceTitle": "Your Balances",
  "faucet.goToPools": "Go to Pools",

  "profile.badge": "YOUR DASHBOARD",
  "profile.title": "Your Profile",
  "profile.subtitle": "Track your pool memberships, NFT badges, and on-chain activity.",
  "profile.connectPrompt": "Connect your wallet to view your Suivan profile.",
  "profile.statsPools": "Pools Joined",
  "profile.statsWon": "Cycles Won",
  "profile.statsSaved": "Total Saved",
  "profile.statsBadges": "Badges Earned",
  "profile.nftTitle": "Suivan Badges & NFTs",
  "profile.nftEmpty": "No badges yet. Join a pool to earn your first Suivan achievement NFT.",
  "profile.activityTitle": "Recent Activity",
  "profile.activityEmpty": "No recent activity. Your pool joins, cycle wins, and badge claims will appear here.",
  "profile.noActivity": "No activity yet. Join a pool to get started!",
  "profile.infoTitle": "Account Info",
  "profile.infoAddress": "Wallet Address",
  "profile.infoMemberSince": "Member Since",
  "profile.infoPools": "Active Pools",
  "profile.infoNetwork": "Network",
};

const id: Record<string, string> = {
  "nav.about": "ROSCA",
  "nav.howItWorks": "Cara Kerja",
  "nav.advantages": "Mengapa Sui",
  "nav.pools": "Pool",
  "nav.faq": "FAQ",
  "nav.yield": "Yield Explorer",

  "ai.badge": "SUI YIELD EXPLORER",
  "ai.title": "SUI Yield Explorer",
  "ai.subtitle": "Data APY langsung dari protokol Sui DeFi — dideploy via arbitrase flash loan DeepBook V3.",
  "ai.loading": "Mengambil data yield...",
  "ai.errorTitle": "KESALAHAN",
  "ai.avgApy": "RATA-RATA APY",
  "ai.maxApy": "APY MAKS",
  "ai.protocols": "PROTOKOL",
  "ai.totalTvl": "TOTAL TVL",
  "ai.protocolYields": "Yield Protokol",
  "ai.trend": "Tren",
  "ai.marketConditions": "Kondisi Pasar",
  "ai.volatilityIndex": "Indeks Volatilitas",
  "ai.gasPrice": "Harga Referensi Gas",
  "ai.direction": "Arah",
  "ai.topProtocol": "Teratas",
  "ai.howSuivanUses": "Bagaimana Suivan Mendeploy Yield",
  "ai.howSuivanUsesDesc": "Dana pool otomatis dideploy ke protokol Sui DeFi via arbitrase flash loan DeepBook V3. Semua eksekusi otomatis — tidak perlu pilih strategi manual. Rute optimal dikalkulasi ulang secara terus-menerus.",
  "ai.step1Title": "Tarik Dana",
  "ai.step1Desc": "Dana pool ditarik secara atomik via hot potato pattern — jika gagal, seluruh transaksi di-rollback.",
  "ai.step2Title": "Arbitrase",
  "ai.step2Desc": "Flash loan dipinjam dari DeepBook → arbitrase dieksekusi di DEX dan lending pool secara bersamaan.",
  "ai.step3Title": "Profit",
  "ai.step3Desc": "Profit disetor ke yield_balance — terkumpul untuk jackpot gacha. Principal dikembalikan ke pool.",
  "ai.step4Title": "Jackpot",
  "ai.step4Desc": "Di akhir pool, satu pemenang gacha mengambil semua yield. Bobot ditentukan oleh skor pembayaran tepat waktu.",
  "ai.deepbookTitle": "DeepBook V3 — Live",
  "ai.deepbookMidPrice": "Harga Tengah",
  "ai.deepbookSpread": "Spread",
  "ai.deepbookBidDepth": "Kedalaman Bid",
  "ai.deepbookAskDepth": "Kedalaman Ask",
  "ai.deepbookLink": "Lihat DeepBook Explorer",
  "ai.explorePools": "Jelajahi Pool",
  "ai.sortedBy": "Diurutkan dari",
  "ai.howItWorks": "Bagaimana Suivan Mendeploy Yield",
  "ai.autoNote": "Semua eksekusi otomatis — tidak perlu strategi manual. Rute optimal dikalkulasi ulang secara terus-menerus via arbitrase flash loan.",
  "ai.seeDeepBookFlow": "Lihat Alur Lengkap",
  "demo.badge": "panduan_demo",
  "demo.subtitle": "Lima langkah dari nol hingga yield. Tidak perlu pengetahuan kripto.",
  "demo.step": "Langkah",
  "demo.step1Detail": "Masuk dengan Google via zkLogin. Suivan membuat dompet Sui secara otomatis. Tanpa seed phrase, tanpa ekstensi browser, tanpa biaya gas untuk bergabung pertama.",
  "demo.step1Action": "Coba Login Google",
  "demo.step2Detail": "Jelajahi pool yang tersedia (Kecil: 10 USDC, Sedang: 50 USDC, Besar: 100 USDC). Setor jaminan sekali — komitmen Anda ke grup. Transaksi disponsori berarti Anda membayar NOL gas.",
  "demo.step2Action": "Gabung Sponsored",
  "demo.step3Detail": "Setiap siklus, setorkan bagian Anda. Suivan melacak setoran per siklus — tidak ada eksploitasi setoran ganda. Tidak bayar? Jaminan dipotong secara proporsional.",
  "demo.step3Action": "Lakukan Setoran",
  "demo.step4Detail": "Satu peserta memenangkan pool setiap siklus. Seleksi menggunakan entropi on-chain (tx digest + timestamp). Pemenang menerima semua setoran siklus + bonus yield.",
  "demo.step4Action": "Pilih Pemenang",
  "demo.step5Detail": "Dana idle pool dialihkan ke protokol DeFi Sui (Cetus, NAVI, Scallop) untuk yield. Sinyal APY dari DeFiLlama — data nyata, hasil nyata. Setelah semua siklus selesai, jaminan dikembalikan.",
  "demo.step5Action": "Lihat Dashboard Yield",
  "demo.feature1Title": "Biaya Gas Nol",
  "demo.feature1Desc": "Transaksi disponsori — gabung pool tanpa memiliki SUI.",
  "demo.feature2Title": "Yield DeFi",
  "demo.feature2Desc": "Dana idle dialihkan ke protokol Sui — APY nyata dari DeFiLlama.",
  "demo.feature3Title": "Metadata On-Chain",
  "demo.feature3Desc": "Detail pool disimpan di Walrus — permanen, terdesentralisasi.",
  "leaderboard.badge": "LEADERBOARD",
  "leaderboard.title": "Peringkat Peserta",
  "leaderboard.subtitle": "Peringkat berdasarkan ketepatan pembayaran, yield, dan reputasi komunitas. Bayar sebelum tanggal 20 untuk naik peringkat.",
  "leaderboard.statPools": "POOL AKTIF",
  "leaderboard.statUsers": "ANGGOTA",
  "leaderboard.statEarned": "TOTAL YIELD",
  "leaderboard.statAvgApy": "RATA APY",
  "leaderboard.tierDiamond": "Berlian",
  "leaderboard.tierPlatinum": "Platinum",
  "leaderboard.tierGold": "Emas",
  "leaderboard.tierSilver": "Perak",
  "leaderboard.tierBronze": "Perunggu",
  "leaderboard.tierDesc": "Anggota dengan rekor pembayaran luar biasa dan akumulasi yield tinggi.",
  "leaderboard.cycleTitle": "Siklus Saat Ini",
  "leaderboard.cycleDeadline": "Batas Pembayaran",
  "leaderboard.cycleDrawing": "Pengundian Pemenang",
  "leaderboard.cyclePot": "Hadiah Pemenang",
  "leaderboard.yourRank": "Peringkat Anda",
  "leaderboard.yourPoints": "Poin",
  "leaderboard.yourYield": "Yield Anda",
  "leaderboard.yourTier": "Tingkat Anda",
  "leaderboard.notConnected": "Hubungkan dompet untuk melihat peringkat",
  "leaderboard.rank": "PERINGKAT",
  "leaderboard.member": "ANGGOTA",
  "leaderboard.tier": "TINGKAT",
  "leaderboard.points": "POIN",
  "leaderboard.payment": "PEMBAYARAN",
  "leaderboard.yield": "YIELD",
  "leaderboard.onTime": "TEPAT WAKTU",
  "leaderboard.pools": "POOL",
  "leaderboard.early": "Tepat Waktu",
  "leaderboard.late": "Terlambat",
  "leaderboard.noData": "Belum ada peserta. Gabung pool untuk muncul di papan peringkat.",
  "leaderboard.rulesTitle": "Cara Peringkat Bekerja",
  "leaderboard.rulesPayment": "Iuran Bulanan",
  "leaderboard.rulesPaymentDesc": "Setiap anggota membayar iuran bulanan. Pembayaran harus diterima sebelum tanggal 20. Pembayaran terlambat dipotong dari collateral.",
  "leaderboard.rulesPoints": "Sistem Poin",
  "leaderboard.rulesPointsDesc": "Bayar 1–10: +100 pts | 11–15: +75 pts | 16–20: +50 pts | Setelah 20 (telat): +10 pts. Poin kumulatif menentukan tingkat Anda.",
  "leaderboard.rulesDrawing": "Pengundian Pemenang",
  "leaderboard.rulesDrawingDesc": "Setiap tanggal 25, satu anggota dipilih secara acak untuk menerima total pot (peserta × iuran bulanan). Semua anggota tetap dalam siklus.",
  "leaderboard.rulesYield": "Perhitungan Yield",
  "leaderboard.rulesYieldDesc": "Dua yield di akhir siklus: (1) Yield Collateral — hasil dasar × pengali tingkat. (2) Yield Kumulatif — dikumpulkan dari semua iuran bulanan. Tingkat lebih tinggi = pengali lebih besar.",
  "leaderboard.rulesGacha": "Jackpot Gacha",
  "leaderboard.rulesGachaDesc": "Semua yield kumulatif dari iuran bulanan dikumpulkan menjadi jackpot. Di akhir pool, satu pemenang diundi via lotere berbobot. Skor pembayaran tepat waktu menentukan jumlah tiket Anda — semakin konsisten, semakin tinggi peluang. Anggota yang melewatkan 2+ pembayaran kehilangan semua eligibilitas gacha.",
  "leaderboard.cta": "Gabung Pool",

  "nav.simulator": "Simulator",

  "simulator.badge": "SIMULATOR",
  "simulator.title": "Berapa saldo dompet yang dibutuhkan?",
  "simulator.subtitle": "Hitung persis berapa USDC + SUI yang Anda perlukan sebelum bergabung dengan pool ROSCA. Tanpa kejutan, tanpa biaya tersembunyi.",
  "simulator.poolConfig": "Konfigurasi Pool",
  "simulator.depositLabel": "Setoran per Siklus (USDC)",
  "simulator.participantsLabel": "Jumlah Peserta",
  "simulator.cycleLabel": "Durasi Siklus (hari)",
  "simulator.gasSponsor": "Transaksi Disponsori",
  "simulator.gasSponsorDesc": "Gabung pertama gratis — disponsori Suivan. Tx berikutnya ~0,0001 SUI per transaksi.",
  "simulator.breakdown": "Rincian Kebutuhan Dompet",
  "simulator.totalUpfront": "Total Dana Dibutuhkan",
  "simulator.needToPrepare": "Anda perlu menyiapkan",
  "simulator.deposit": "Setoran Siklus",
  "simulator.collateral": "Jaminan (125%)",
  "simulator.gas": "Biaya Gas",
  "simulator.gasFree": "Gabung pertama disponsori",
  "simulator.usdc": "USDC",
  "simulator.sui": "SUI",
  "simulator.poolSummary": "Ringkasan Pool",
  "simulator.totalPool": "Total Nilai Pool",
  "simulator.totalCycles": "Total Siklus",
  "simulator.poolDuration": "Durasi Pool",
  "simulator.yourPosition": "Posisi Anda",
  "simulator.youPay": "Bayar Per Siklus",
  "simulator.youEarn": "Total yang Anda Terima",
  "simulator.compareTitle": "Gas ultra-rendah di Sui",
  "simulator.compareDesc": "Biaya tx Sui ~0,0001 SUI (pecahan sen). Ethereum L1 rata-rata ~$1,50 per tx.",
  "simulator.suiFee": "Biaya Sui",
  "simulator.ethFee": "Biaya Ethereum",
  "simulator.savings": "Efisiensi",
  "simulator.cta": "Jelajahi Pool Nyata",
  "simulator.collateralNote": "125% dari sisa komitmen kontribusi, dikembalikan di akhir siklus",
  "simulator.collateralDetail": "Jaminan melindungi semua anggota. Jika kamu melewatkan pembayaran, setoran dipotong dari jaminan. Jaminan yang tidak digunakan + yield proporsional dikembalikan saat pool berakhir.",

  "faucet.badge": "FAUCET TEST",
  "faucet.title": "Dapatkan Token Tes",
  "faucet.subtitle": "Langkah 1: Dapatkan SUI gratis untuk gas. Langkah 2: Klaim 500 USDC untuk testing. Lalu jelajahi pool Suivan sebelum mainnet.",
  "faucet.claimUsdc": "Klaim 10,000 Test USDC",
  "faucet.claimSui": "Klaim 1 Test SUI",
  "faucet.walletRequired": "Hubungkan dompet Anda untuk klaim token tes.",
  "faucet.success": "Token berhasil diklaim!",
  "faucet.error": "Permintaan faucet gagal",
  "faucet.cooldown": "Cooldown aktif. Coba lagi dalam {time}s.",
  "faucet.description": "Semua token di halaman ini hanya testnet \u2014 tidak bernilai riil. Gunakan untuk simulasi pembuatan pool, join, dan yield.",
  "faucet.usdcLabel": "USDC (Testnet)",
  "faucet.usdcDesc": "Stablecoin USDC untuk deposit dan jaminan pool",
  "faucet.suiLabel": "TEST_SUI",
  "faucet.suiDesc": "SUI untuk biaya gas (transaksi pertama gratis)",
  "faucet.recentTitle": "Klaim Terbaru",
  "faucet.recentEmpty": "Belum ada klaim. Mulai dengan menghubungkan dompet Anda.",
  "faucet.balanceTitle": "Saldo Anda",
  "faucet.goToPools": "Ke Pools",

  "profile.badge": "DASHBOARD ANDA",
  "profile.title": "Profil Anda",
  "profile.subtitle": "Pantau keanggotaan pool, lencana NFT, dan aktivitas on-chain Anda.",
  "profile.connectPrompt": "Hubungkan dompet Anda untuk melihat profil Suivan.",
  "profile.statsPools": "Pool Diikuti",
  "profile.statsWon": "Siklus Menang",
  "profile.statsSaved": "Total Ditabung",
  "profile.statsBadges": "Lencana",
  "profile.nftTitle": "Lencana & NFT Suivan",
  "profile.nftEmpty": "Belum ada lencana. Gabung pool untuk dapatkan NFT pencapaian Suivan pertama Anda.",
  "profile.activityTitle": "Aktivitas Terbaru",
  "profile.activityEmpty": "Belum ada aktivitas. Join pool, menang siklus, dan klaim badge akan muncul di sini.",
  "profile.noActivity": "Belum ada aktivitas. Gabung pool untuk memulai!",
  "profile.infoTitle": "Info Akun",
  "profile.infoAddress": "Alamat Dompet",
  "profile.infoMemberSince": "Anggota Sejak",
  "profile.infoPools": "Pool Aktif",
  "profile.infoNetwork": "Jaringan",
};

const translations: Record<Language, Record<string, string>> = { en, id };

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const stored = localStorage.getItem("suivan-language") as Language | null;
    return stored === "en" || stored === "id" ? stored : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("suivan-language", lang);
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language]?.[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t } as LanguageContextType}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
